chore(integrations): move pynamodb,pyodbc,pyramid,redis,rediscluster,requests to internal
DataDog/dd-trace-py pull request #10204
Opened 2024-08-13 17:29 UTC by rachelyangdog

- Moves all integration internals in ddtrace/contrib/(integration name)/ to ddtrace/contrib/internal/(integration name)/ for pynamodb, pyodbc, pyramid, redis, rediscluster, and requests
- Ensures ddtrace/contrib/(integration name)/ and ddtrace/contrib/(integration name)/ continue to expose the same functions, classes, imports, and module level variables (via from ..internal.integration.module import * imports).
- Log a deprecation warning if internal modules in ddtrace/contrib/(integration name)/ and ddtrace/contrib/(integration name)/. Only patch and unpack methods should be exposed by these packages.
- https://github.com/DataDog/dd-trace-py/pull/9996

## Checklist
- [ ] PR author has checked that all the criteria below are met
- The PR description includes an overview of the change
- The PR description articulates the motivation for the change
- The change includes tests OR the PR description describes a testing strategy
- The PR description notes risks associated with the change, if any
- Newly-added code is easy to change
- The change follows the [library release note guidelines](https://ddtrace.readthedocs.io/en/stable/releasenotes.html)
- The change includes or references documentation updates if necessary
- Backport labels are set (if [applicable](https://ddtrace.readthedocs.io/en/latest/contributing.html#backporting))

## Reviewer Checklist
- [ ] Reviewer has checked that all the criteria below are met 
- Title is accurate
- All changes are related to the pull request's stated goal
- Avoids breaking [API](https://ddtrace.readthedocs.io/en/stable/versioning.html#interfaces) changes
- Testing strategy adequately addresses listed risks
- Newly-added code is easy to change
- Release note makes sense to a user of the library
- If necessary, author has acknowledged and discussed the performance implications of this PR as reported in the benchmarks PR comment
- Backport labels are set in a manner that is consistent with the [release branch maintenance policy](https://ddtrace.readthedocs.io/en/latest/contributing.html#backporting)

2024-08-13 18:32 UTC, taegyunkim requested changes
Looks like pyramid circle ci tests are failing

2024-08-14 13:51 UTC, emmettbutler approved these changes

2024-08-14 18:44 UTC, mabdinur commented on ddtrace/contrib/internal/pyramid/patch.py
> +    setattr(pyramid.config, DD_PATCH, True)
```suggestion
    if getattr(pyramid, DD_PATCH, False):
        return
    setattr(pyramid, DD_PATCH, True)
```

2024-08-14 21:06 UTC, mabdinur approved these changes

2024-08-14 21:10 UTC, mabdinur approved these changes

2024-08-14 21:53 UTC, wconti27 approved these changes

2024-08-15 14:20 UTC, taegyunkim approved these changes

2024-08-15 16:55 UTC, merged