fix(core): add level of indirection for provider.py contetvars
DataDog/dd-trace-py pull request #10525
Opened 2024-09-05 14:49 UTC by sanchda

Whenever a contextvar is reassociated, it causes the underlying HAMT data structure to clone a node.  This clone operation requires de-referencing stored Python objects, which can cause segmentation faults if other libraries mis-manage the reference counts for their objects, causing them to be GC'd.

This patch stores a single wrapper object into the contextvar, then manipulates a reference within that wrapper in order to propagate our desired information.  In our normal testing fixture, we cause as many as 69 realloc (and clone) events in a single process (I infer this by patching cpython itself to produce a log).  With this patch, that number is down to 1, and it doesn't originate from this provider.py

## Checklist
- [X] PR author has checked that all the criteria below are met
- The PR description includes an overview of the change
- The PR description articulates the motivation for the change
- The change includes tests OR the PR description describes a testing strategy
- The PR description notes risks associated with the change, if any
- Newly-added code is easy to change
- The change follows the [library release note guidelines](https://ddtrace.readthedocs.io/en/stable/releasenotes.html)
- The change includes or references documentation updates if necessary
- Backport labels are set (if [applicable](https://ddtrace.readthedocs.io/en/latest/contributing.html#backporting))

## Reviewer Checklist
- [ ] Reviewer has checked that all the criteria below are met 
- Title is accurate
- All changes are related to the pull request's stated goal
- Avoids breaking [API](https://ddtrace.readthedocs.io/en/stable/versioning.html#interfaces) changes
- Testing strategy adequately addresses listed risks
- Newly-added code is easy to change
- Release note makes sense to a user of the library
- If necessary, author has acknowledged and discussed the performance implications of this PR as reported in the benchmarks PR comment
- Backport labels are set in a manner that is consistent with the [release branch maintenance policy](https://ddtrace.readthedocs.io/en/latest/contributing.html#backporting)

2024-09-05 14:57 UTC, emmettbutler commented
interesting and promising

2024-09-05 15:49 UTC, taegyunkim commented
Could you run `hatch run lint:fmt` to format and trigger the rest of circle ci?

2024-09-06 07:23 UTC, r1viollet commented on ddtrace/_trace/provider.py
> +        self._context_var.set(value)
It seems like we removed the wrapper along the way ?
The aim was to have `self._context_var.get().wrapper_set(value)`
I am not sure why we got rid of it ?

2024-09-06 17:14 UTC, Yun-Kim reviewed
Just to help my understanding, would you be able to update the PR description with a small snippet example of a reassoc event that would trigger a segfault/corruption? Thanks!

2024-09-06 17:31 UTC, sanchda commented
> Just to help my understanding, would you be able to update the PR description with a small snippet example of a reassoc event that would trigger a segfault/corruption? Thanks!

Unfortunately, _any_ `ContextVar.set()` operation will trigger a re-association.  The sad truth of the matter is that CPython's implementation of ContextVars bleeds a lot of common state together.  I have a standalone reproduction [here](https://github.com/sanchda/systems_experiments/tree/main/contextvar_segfault).  I'll link it in the PR description.

2024-09-09 08:29 UTC, r1viollet commented
I agree with the code, but I still can not understand why I get a different type of context within greenlets.
I now get an actual context (and not a span). I am not sure what is the expected behaviour.

2024-09-11 08:45 UTC, r1viollet approved these changes
LGTM

2024-09-11 20:37 UTC, Yun-Kim reviewed
This PR makes sense to me but I must admit I'm not nuanced in contextvars internals enough to give a more thoughtful review here. Is this not an issue with CPython's implementation of ContextVars, and if so, should it be fixed upstream?

2024-09-13 13:29 UTC, r1viollet commented
> This PR makes sense to me but I must admit I'm not nuanced in contextvars internals enough to give a more thoughtful review here. Is this not an issue with CPython's implementation of ContextVars, and if so, should it be fixed upstream?

I agree there could be an effort to understand what objects have lifetime issues. Though we still have to mitigate in the short term.

2024-09-19 15:53 UTC, sanchda commented
I dropped this PR for a while because we shipped a patch to some affected customers and it didn't directly fix the issue we saw.  However, it did reveal more information about where bad objects were being consumed.  I count that as a net win.

So, I'd like to summarize the benefits of this PR as the following
* Fewer clone operations means better performance
* Protects us from cpython global state
* ... and in so doing, makes crashes more actionable


@Yun-Kim:
> This PR makes sense to me but I must admit I'm not nuanced in contextvars internals enough to give a more thoughtful review here. Is this not an issue with CPython's implementation of ContextVars, and if so, should it be fixed upstream?

I don't know whether I'd call it an issue in the implementation or the design.  There are a few problems here.
* CPython directly uses the system allocator--it doesn't manage objects through the kind of indirection that the JVM does, so it's entirely possible for misbehaving code to convert a strong ref (e.g., a contextvar) into a weak ref, causing issues to propagate.  Solving this problem in a durable way would be extremely difficult.
* Even if the CPython maintainers did treat this as an implementation issue, they will not backport such a fix to versions which we currently support (e.g., 3.9).  That means we're on the hook for dealing with those versions safely.  I think this PR does that.

2024-09-30 07:51 UTC, r1viollet commented
Should we merge this to progress and get better stacks on associated crashes ?

2024-09-30 15:45 UTC, wconti27 approved these changes

2024-09-30 15:49 UTC, wconti27 requested changes
Going to let @emmettbutler handle this review

2024-09-30 17:19 UTC, emmettbutler approved these changes

2024-09-30 17:19 UTC, emmettbutler commented on releasenotes/notes/fix-contextvar-cloning-49adaf7fdf36e8fb.yaml
> +    Fixes an issue where normal tracer operation could cause items stored by other libraries to be dereferenced by the
```suggestion
    Fixes an issue where normal library use could cause items stored by other libraries to be dereferenced by the
```

2024-09-30 17:19 UTC, emmettbutler commented on ddtrace/_trace/provider.py
> +    ContextVar storage from a strong to a weak reference. When such objects are de-referenced--as they would be when
```suggestion
    ContextVar storage from a strong to a weak reference). When such objects are de-referenced--as they would be when
```

2024-10-01 13:43 UTC, sanchda commented
@wconti27 thanks for bringing @emmettbutler into the discussion--can you toggle your review?  Merges are currently blocked since your last review required changes.  🙇

2024-10-01 13:45 UTC, wconti27 approved these changes

2024-10-03 17:29 UTC, sanchda commented
/merge

2024-10-03 17:45 UTC, ZStriker19 approved these changes

2024-10-03 20:42 UTC, taegyunkim commented
Whenever I see failing tests in CI for this PR, I've been pushing retry button. I've pressed the button enough number of times to believe those are actual failures.

2024-10-04 14:31 UTC, sanchda commented
> Whenever I see failing tests in CI for this PR, I've been pushing retry button. I've pressed the button enough number of times to believe those are actual failures.

but what if it passes if I retry just one more time (jk, checking)

2025-01-23 00:06 UTC, closed without merging