feat(iast): ast deny list
DataDog/dd-trace-py pull request #10540
Opened 2024-09-06 13:07 UTC by avara1986

## Checklist
- [ ] PR author has checked that all the criteria below are met
- The PR description includes an overview of the change
- The PR description articulates the motivation for the change
- The change includes tests OR the PR description describes a testing strategy
- The PR description notes risks associated with the change, if any
- Newly-added code is easy to change
- The change follows the [library release note guidelines](https://ddtrace.readthedocs.io/en/stable/releasenotes.html)
- The change includes or references documentation updates if necessary
- Backport labels are set (if [applicable](https://ddtrace.readthedocs.io/en/latest/contributing.html#backporting))

## Reviewer Checklist
- [ ] Reviewer has checked that all the criteria below are met 
- Title is accurate
- All changes are related to the pull request's stated goal
- Avoids breaking [API](https://ddtrace.readthedocs.io/en/stable/versioning.html#interfaces) changes
- Testing strategy adequately addresses listed risks
- Newly-added code is easy to change
- Release note makes sense to a user of the library
- If necessary, author has acknowledged and discussed the performance implications of this PR as reported in the benchmarks PR comment
- Backport labels are set in a manner that is consistent with the [release branch maintenance policy](https://ddtrace.readthedocs.io/en/latest/contributing.html#backporting)

2024-09-11 10:57 UTC, juanjux requested changes
Blocking for now. I don't see the logic of banning all these modules, some of them look like could have propagation if properly patched, so I want to discuss that first.

2024-09-11 10:58 UTC, gnufede commented on ddtrace/appsec/_iast/_ast/ast_patching.py
> +    "asgiref.current_thread_executor",
If we add `"asgiref"` to the denylist, we don't need to add the submodules. This applies to `asyncio`, `backports`, `boto3`, `charset_normalizer`, `concurrent` and `django` as well

2024-09-11 10:58 UTC, gnufede commented on ddtrace/appsec/_iast/_ast/ast_patching.py
> +    "concurrent",
```suggestion
    "concurrent",
```

2024-09-12 10:17 UTC, juanjux approved these changes

2024-09-12 10:20 UTC, gnufede commented on ddtrace/appsec/_iast/_ast/ast_patching.py
> +    "django.urls.utils",
As mentioned before, we don't need to include submodules if the parent is included

```suggestion
    "django.urls",
```

2024-09-12 10:21 UTC, gnufede commented on ddtrace/appsec/_iast/_ast/ast_patching.py
> +    "django_filters.utils",
Ditto
```suggestion
    "django_filters",
```

2024-09-12 10:21 UTC, gnufede commented on ddtrace/appsec/_iast/_ast/ast_patching.py
> +    "django_filters.widgets",
Ditto
```suggestion
    "django_filters",
```

2024-09-12 11:39 UTC, gnufede commented on ddtrace/appsec/_iast/_ast/ast_patching.py
> -    "django.views",
Is this change on purpose? It's not a change from the peer review

2024-09-12 13:06 UTC, gnufede approved these changes

2024-09-13 08:16 UTC, merged