chore(requests): fix local test runs
DataDog/dd-trace-py pull request #10769
Opened 2024-09-24 02:41 UTC by mabdinur

## Checklist
- [ ] PR author has checked that all the criteria below are met
- The PR description includes an overview of the change
- The PR description articulates the motivation for the change
- The change includes tests OR the PR description describes a testing strategy
- The PR description notes risks associated with the change, if any
- Newly-added code is easy to change
- The change follows the [library release note guidelines](https://ddtrace.readthedocs.io/en/stable/releasenotes.html)
- The change includes or references documentation updates if necessary
- Backport labels are set (if [applicable](https://ddtrace.readthedocs.io/en/latest/contributing.html#backporting))

## Reviewer Checklist
- [ ] Reviewer has checked that all the criteria below are met 
- Title is accurate
- All changes are related to the pull request's stated goal
- Avoids breaking [API](https://ddtrace.readthedocs.io/en/stable/versioning.html#interfaces) changes
- Testing strategy adequately addresses listed risks
- Newly-added code is easy to change
- Release note makes sense to a user of the library
- If necessary, author has acknowledged and discussed the performance implications of this PR as reported in the benchmarks PR comment
- Backport labels are set in a manner that is consistent with the [release branch maintenance policy](https://ddtrace.readthedocs.io/en/latest/contributing.html#backporting)

2024-09-24 14:51 UTC, emmettbutler requested changes

2024-09-24 14:51 UTC, emmettbutler commented on tests/contrib/requests/test_requests.py
> -HOST_AND_PORT = "httpbin-local:8001"
This change would break the test in gitlab, if I recall correctly.

2024-09-24 15:02 UTC, mabdinur commented on tests/contrib/requests/test_requests.py
> -HOST_AND_PORT = "httpbin-local:8001"
The requests tests seem to be passing: https://gitlab.ddbuild.io/DataDog/apm-reliability/dd-trace-py/-/jobs/649783641

2024-09-25 14:43 UTC, brettlangdon approved these changes

2024-09-25 15:12 UTC, emmettbutler approved these changes

2024-09-25 17:14 UTC, merged