Add option for simpler GraphQL resource names
DataDog/dd-trace-py pull request #10886
Opened 2024-10-01 16:26 UTC by goodspark

The current ddtrace GraphQL integration sets the full query as the resource name. This is fragile for monitoring and metrics purposes because a simple field change will result in a completely new name. In addition, it's kind of unsightly to see a resource name that's so long.

As an example, take a look at [ddtrace-graphql](https://github.com/beezz/ddtrace-graphql). Normally, I'd just use that, but it's out of date and incompatible with the latest versions of ddtrace as well as graphql.

Addresses #10875

## Checklist
- [ ] PR author has checked that all the criteria below are met
- The change includes tests OR the PR description describes a testing strategy
- Newly-added code is easy to change
- The change follows the [library release note guidelines](https://ddtrace.readthedocs.io/en/stable/releasenotes.html)
- The change includes or references documentation updates if necessary

## Reviewer Checklist
- [ ] Reviewer has checked that all the criteria below are met 
- Title is accurate
- All changes are related to the pull request's stated goal
- Avoids breaking [API](https://ddtrace.readthedocs.io/en/stable/versioning.html#interfaces) changes
- Testing strategy adequately addresses listed risks
- Newly-added code is easy to change
- Release note makes sense to a user of the library
- If necessary, author has acknowledged and discussed the performance implications of this PR as reported in the benchmarks PR comment
- Backport labels are set in a manner that is consistent with the [release branch maintenance policy](https://ddtrace.readthedocs.io/en/latest/contributing.html#backporting)

2024-10-07 20:53 UTC, erikayasuda requested changes

2024-10-08 06:28 UTC, goodspark commented on tests/snapshots/tests.contrib.graphql.test_graphql.test_simple_resource_names[query-name].json
> +    "resource": "query Name",
This is the key thing - the resource name excludes the args and body.

2024-10-08 06:28 UTC, goodspark commented on tests/snapshots/tests.contrib.graphql.test_graphql.test_simple_resource_names[no-name].json
> +    "resource": "query { hello }",
For queries that aren't named, simplifying will be odd so they're left as-is.

2024-10-08 06:28 UTC, goodspark commented on ddtrace/contrib/internal/graphql/patch.py
> +    if config.graphql.simplify_resource:
Sure, added them.

2025-01-02 20:57 UTC, marcotc commented
I don't recommend adding a new option (`DD_TRACE_GRAPHQL_SIMPLIFY_RESOURCE_NAME`) in this fashion today because we have an active workstream working on improving GraphQL visibility, including improving the resource naming. 
The new default might be `query Name`, but we are not sure yet, but we'll built supporting tools around the new desired behavior (e.g. Datadog app improvements like syntax highlighting) so we don't want users to migrate to an option that might provide subpar observability in the near future.

2025-04-14 17:25 UTC, closed without merging