Lambda extension support
DataDog/dd-trace-py pull request #2092
Opened 2021-03-02 17:02 UTC by DarcyRaynerDD

## Description
Adds support for submitting traces via the Datadog Lambda Extension. The Datadog Lambda Extension is a special flavor of the datadog agent, the hooks into the AWS Lambda runtime. Read the draft RFC on tracing with the extension [here](https://github.com/DataDog/architecture/blob/1721621a36e8ebcecc07ea90cabb4ea4f36173a0/rfcs/serverless/lambda-extension-tracing/rfc.md) for more context.

This PR adds a sync_flush_mode to the AgentWriter, will flush immediately on write. We also change the detection mechanism for the log writer, only selecting it when we detect a serverless environment and the extension isn't present. We use a hardcoded file system path to detect the extension, (due to the way the extension API works, the extension can only be at that path).

I've added unit tests, and tested this manually as well.

## Checklist
- [ ] Added to the correct milestone.
- [ ] Tests provided or description of manual testing performed is included in the code or PR.
- [ ] Library documentation is updated.
- [ ] [Corp site](https://github.com/DataDog/documentation/) documentation is updated (link to the PR).

2021-03-19 17:53 UTC, DarcyRaynerDD commented
@Kyle-Verhoog Can I get a review on this PR?

2021-03-19 18:51 UTC, Kyle-Verhoog commented
Yes! Apologies for the delay @DarcyRaynerDD I'll have a look by EOD.

2021-03-22 14:59 UTC, Kyle-Verhoog reviewed
Looks good! I'm going to pull out the synchronous writer change to a separate PR and add a few additional test cases but I think the general approach makes sense :+1:

2021-03-23 18:27 UTC, Yun-Kim approved these changes

2021-03-23 18:48 UTC, Yun-Kim requested changes

2021-03-23 18:48 UTC, Yun-Kim commented on ddtrace/tracer.py
> +        sync_mode = self._is_agentless_environment()
A quick comment above explaining why being in an agentless environment triggers synchronous flush mode would be beneficial for future readers

2021-03-24 17:44 UTC, Yun-Kim approved these changes

2021-03-29 15:36 UTC, P403n1x87 approved these changes

2021-03-29 16:03 UTC, merged