fix: avoid serialization issue with psycopg2
DataDog/dd-trace-py pull request #2229
Opened 2021-03-25 12:34 UTC by majorgreys

## Description

## Checklist
- [ ] Added to the correct milestone.
- [ ] Tests provided or description of manual testing performed is included in the code or PR.
- [ ] Library documentation is updated.
- [ ] [Corp site](https://github.com/DataDog/documentation/) documentation is updated (link to the PR).

2021-04-26 13:47 UTC, jd requested changes
what issue? description? test? 😢

2021-04-26 14:49 UTC, majorgreys commented
This is a potential mitigation that is blocked on feedback from a user which I have had difficulty reproducing with a test case. Hoping that with confirmation of the mitigation we can work out a scenario for reproducing it.

2021-05-13 13:42 UTC, brettlangdon requested changes

2021-05-13 13:42 UTC, brettlangdon commented on .circleci/config.yml
> -  deploy_docs:
if you are removing this, can you move to it's own PR?

2021-05-13 13:42 UTC, brettlangdon commented on scripts/build-dist-cp27
> +#!/usr/bin/env bash
these changes should be in their own PR.

also, do we still need this workflow? we get wheel building in GitHub Actions, and we have means of publishing dev builds to PyPI, we shouldn't need manual building/artifacts from CircleCI?

2021-05-13 13:42 UTC, brettlangdon commented on ddtrace/contrib/psycopg/connection.py
> +            s.resource = stringify(query)
this change looks fine, but the other stuff needs to be separated out.

2021-05-13 13:43 UTC, brettlangdon commented
is this meant to be merged into `0.44` as a backport?

2021-05-13 13:44 UTC, majorgreys commented
@brettlangdon, sorry please ignore this PR. It's to isolate a problem and I'll close it when I've built the wheel.

2021-05-13 13:44 UTC, closed without merging