Explicitly add integration config in bottle
DataDog/dd-trace-py pull request #2235
Opened 2021-03-25 21:38 UTC by Yun-Kim

## Description
From #2223, it was found that the `bottle` integration did not declare its own integration config and instead relied on storing `use_distributed_tracing` in the app object. To unify integrations to follow the same pattern, an integration config was added to bottle with the `distributed_tracing` setting set to True by default, and changing the attribute itself to ahve getter/setters as a property within the app class.

## Checklist
- [ ] Added to the correct milestone.
- [ ] Tests provided or description of manual testing performed is included in the code or PR.
- [ ] Library documentation is updated.
- [ ] [Corp site](https://github.com/DataDog/documentation/) documentation is updated (link to the PR).

2021-03-25 21:50 UTC, Kyle-Verhoog commented on ddtrace/contrib/bottle/trace.py
>      def __init__(self, service="bottle", tracer=None, distributed_tracing=True):
```suggestion
    def __init__(self, service="bottle", tracer=None, distributed_tracing=None):
```

2021-03-25 21:50 UTC, Kyle-Verhoog commented on ddtrace/contrib/bottle/trace.py
>          self.distributed_tracing = distributed_tracing
```suggestion
        if distributed_tracing is not None:
            config.bottle.distributed_tracing = distributed_tracing
```

2021-03-25 21:50 UTC, Kyle-Verhoog commented on ddtrace/contrib/bottle/trace.py
> +        return config.bottle.get("distributed_tracing", True)
```suggestion
        return config.bottle.distributed_tracing
```

The default is included in the config definition

2021-04-13 17:01 UTC, Kyle-Verhoog requested changes
Just one test case with the env var and this is good to go

2021-04-13 17:01 UTC, Kyle-Verhoog commented on tests/contrib/bottle/test_distributed.py
Just need a test case that uses the DD_BOTTLE_DISTRIBUTED_TRACING environment variable

2021-04-19 18:11 UTC, majorgreys approved these changes

2021-04-19 18:11 UTC, merged