Add integration config for tornado, refactor distributed tracing helper usage
DataDog/dd-trace-py pull request #2293
Opened 2021-04-08 22:09 UTC by Yun-Kim

## Description
From #2223, it was found that the tornado integration did not declare its own integration config and instead relied on storing use_distributed_tracing in the app settings object. To unify integrations to follow the same pattern, an integration config was added to tornado with the distributed_tracing setting set to True by default. Additionally, the `activate_distributed_headers` helper from `trace_utils` was used to refactor the distributed tracing in tornado handlers.

2021-04-08 22:10 UTC, Yun-Kim commented
To do: consider if settings dictionary in `tornado/application.py` can be refactored to use the integration config object

2021-04-16 14:20 UTC, Kyle-Verhoog requested changes

2021-04-16 14:20 UTC, Kyle-Verhoog commented on releasenotes/notes/tornado-int-config-a8900a60201d4d61.yaml
> +    Added distributed tracing setting to integration config for tornado.
Need to be a bit more specific again

2021-04-16 14:20 UTC, Kyle-Verhoog commented on ddtrace/contrib/tornado/patch.py
> +        distributed_tracing=asbool(get_env("tornado", "distributed_tracing", default=True)),
Need tests for this

2021-04-19 21:13 UTC, Yun-Kim commented
> For this reason, I don't want to add the env variable unless we're actively going to remove the `settings.distributed_tracing` option.

My solution for this was to make `settings.distributed_tracing`  default to `None`, and use the environment variable `DD_TORNADO_DISTRIBUTED_TRACING` default to `True` and referenced by `config.tornado.distributed_tracing`. This way, nothing functionally changes as it will by default propagate distributed traces, but now will rely on the int_config by default. If any user makes any changes to their `settings.distributed_tracing`, this will override the int_config and env var.

2021-04-20 16:53 UTC, Kyle-Verhoog approved these changes
nice job! lgtm

2021-04-20 16:53 UTC, Kyle-Verhoog commented on ddtrace/contrib/tornado/__init__.py
> +  ``DD_TORNADO_DISTRIBUTED_TRACING` environment variable.
:+1:

2021-04-20 17:39 UTC, Kyle-Verhoog approved these changes

2021-04-21 22:20 UTC, brettlangdon approved these changes

2021-04-21 22:25 UTC, merged