Only keep approved branches up to date
DataDog/dd-trace-py pull request #2338
Opened 2021-04-20 20:06 UTC by Kyle-Verhoog

We're running a ton of unnecessary CI jobs and this doesn't provide us a
ton of value at the moment as we only merge a few PRs a day.

We can always loosen the requirement in the future in need-be.

2021-04-20 20:19 UTC, brettlangdon commented
I don't think we need to be this strict

2021-04-21 13:38 UTC, P403n1x87 approved these changes
👍

2021-04-21 16:27 UTC, Yun-Kim submitted a review, later dismissed

2021-04-26 15:44 UTC, jd requested changes

2021-04-26 15:44 UTC, jd commented on .mergify.yml
>        update: {}
You can remove this rule altogether then, the `strict: smart` does it automatically.

2021-04-29 17:36 UTC, Kyle-Verhoog commented
Going to close this as it looks like we're ok with things as-is

2021-04-29 17:36 UTC, closed without merging