ci(mysql): move mysql tests to riot
DataDog/dd-trace-py pull request #2340
Opened 2021-04-21 11:15 UTC by P403n1x87

## Description

## Checklist
- [ ] Added to the correct milestone.
- [ ] Tests provided or description of manual testing performed is included in the code or PR.
- [ ] Library documentation is updated.
- [ ] [Corp site](https://github.com/DataDog/documentation/) documentation is updated (link to the PR).

2021-04-21 13:28 UTC, brettlangdon approved these changes

2021-04-21 15:14 UTC, Kyle-Verhoog approved these changes

2021-04-23 14:51 UTC, Kyle-Verhoog commented
Looks like the mysql-connector suite is taking ages to run: https://app.circleci.com/pipelines/github/DataDog/dd-trace-py/7548/workflows/cee29189-b821-44b6-ae18-a230cf9d0952/jobs/644390 (still running)

2021-04-23 15:59 UTC, brettlangdon submitted a review, later dismissed

2021-04-23 16:06 UTC, P403n1x87 commented
> Looks like the mysql-connector suite is taking ages to run: https://app.circleci.com/pipelines/github/DataDog/dd-trace-py/7548/workflows/cee29189-b821-44b6-ae18-a230cf9d0952/jobs/644390 (still running)

I think it's because I forgot to point CircleCI to riot 🤦 . Now that should be fixed.

2021-04-23 16:56 UTC, Kyle-Verhoog requested changes

2021-04-23 16:56 UTC, Kyle-Verhoog commented on riotfile.py
> +                    pkgs={"mysql-connector": ["8.0", ">=8.0", "latest"]},
```suggestion
                    pkgs={"mysql-connector": ["8.0", ">=8.0", latest]},
```

2021-04-26 14:14 UTC, brettlangdon approved these changes

2021-04-26 15:03 UTC, Kyle-Verhoog approved these changes

2021-04-26 15:04 UTC, merged