feat(cassandra): add support for latest
DataDog/dd-trace-py pull request #2634
Opened 2021-07-09 10:36 UTC by P403n1x87

## Description

## Checklist
- [ ] Added to the correct milestone.
- [ ] Tests provided or description of manual testing performed is included in the code or PR.
- [ ] Library documentation is updated.
- [ ] [Corp site](https://github.com/DataDog/documentation/) documentation is updated (link to the PR).

2021-07-09 15:29 UTC, jd approved these changes

2021-07-12 08:41 UTC, nizox approved these changes

2021-07-12 13:20 UTC, Kyle-Verhoog reviewed
:+1: lgtm except for the release note 🙂

2021-07-12 13:20 UTC, Kyle-Verhoog commented on releasenotes/notes/cassandra-latest-3-79c9f21c080bd1c6.yaml
> +    Added support for the latest Cassandra release.
Don't think it's worth the release note as we already mention in our docs that we support cassandra 3.5 and above - maybe makes sense as a `fix` (and maybe mention which specific versions we fixed)

```suggestion
```

2021-07-19 09:00 UTC, jd approved these changes

2021-07-20 14:21 UTC, brettlangdon requested changes
remove release note then 👍🏻

2021-07-22 12:46 UTC, brettlangdon approved these changes

2021-07-22 12:47 UTC, Kyle-Verhoog approved these changes

2021-07-22 14:50 UTC, Kyle-Verhoog approved these changes

2021-07-22 21:06 UTC, brettlangdon approved these changes

2021-07-22 21:20 UTC, merged