Update trace propagation format for botocore direct invocations
DataDog/dd-trace-py pull request #2639
Opened 2021-07-12 18:33 UTC by agocs

## Description

Updates the trace propagation format for botocore direct lambda invocations. The old way was:

```
clientContext: {
  custom:{
    _datadog: {
      x-datadog-trace-id: "",
      x-datadog-parent-id: "",
      ...
    }
  }
}
```

New way is:

```
clientContext: {
  custom: {
      x-datadog-trace-id: "",
      x-datadog-parent-id: "",
      ...
  }
}
```

https://docs.google.com/document/d/1pruSeesAr2bAVMtz_rUlsiBZKFoFWdB4nSq5Vuym2l8/edit?usp=sharing

### Reasoning

The Go and Java runtimes only support `ClientContext.custom` fields of type `map[string]string`. C.f. :
- https://github.com/aws/aws-lambda-java-libs/issues/212
- https://github.com/DataDog/dd-trace-js/issues/1312

In order to pass trace contexts to directly invoked Go and Java lambda functions, we can write the trace context key:values to ClientContext.custom rather than creating a ClientContext.custom._datadog object like we've been doing.

### Backwards compatibility

This is, strictly speaking, a breaking change in how we add trace context to direct invocations. The Python and JS repos have already been updated to accept the new format:
- https://github.com/DataDog/datadog-lambda-js/pull/194
- https://github.com/DataDog/datadog-lambda-python/pull/146

They both check for the old and new formats. 

## Checklist
- [x] Added to the correct milestone.
- [x] Tests provided or description of manual testing performed is included in the code or PR.
- [ ] Library documentation is updated.
- [ ] [Corp site](https://github.com/DataDog/documentation/) documentation is updated (link to the PR).

2021-07-12 18:50 UTC, Kyle-Verhoog reviewed
I'm thinking we should leave the old method behind a configuration option since a bunch of users will not be on the latest version of the serverless client(s) 🤔 

Thoughts @agocs?

2021-07-12 20:17 UTC, agocs commented
@Kyle-Verhoog I can get behind that. I considered it, but initially decided against it as this is such a niche change. Definitely happy to add that parameter though. 

Which way do you think the default should go? I was thinking it should favor the new, working trace propagation format.

2021-07-12 20:32 UTC, Kyle-Verhoog commented
> Which way do you think the default should go? I was thinking it should favor the new, working trace propagation format.

Yup - agreed :+1:

The configuration option can be added here: https://github.com/DataDog/dd-trace-py/blob/7e1d82a399c3a2e444c14d2b65f73d738db97064/ddtrace/contrib/botocore/patch.py#L35-L41. We should offer an environment variable too

and then documented here https://github.com/DataDog/dd-trace-py/blob/7e1d82a399c3a2e444c14d2b65f73d738db97064/ddtrace/contrib/botocore/__init__.py#L16-L20

(this will show up here: https://ddtrace.readthedocs.io/en/stable/integrations.html#botocore)


Also an `upgrade` release note entry would be required here which can be created with [reno](https://docs.openstack.org/reno/latest/):

 ```shell
$ reno new botocore
```

2021-07-12 20:34 UTC, agocs commented
Awesome! I appreciate it!

2021-07-14 20:15 UTC, agocs commented
@Kyle-Verhoog Changes made! Thanks. Should I drop a link to this in the apm-python channel?

2021-07-15 14:21 UTC, Kyle-Verhoog requested changes
:+1: solid tests - thanks for also keeping a test with the old setting! Just some suggestions around the user-facing aspects 🙂

2021-07-15 15:11 UTC, agocs commented on ddtrace/contrib/botocore/patch.py
> +            "botocore", "clientcontext_custom_add_datadog_object", default=False
`invoke_with_legacy_context` ?

2021-07-15 16:10 UTC, agocs commented on ddtrace/contrib/botocore/__init__.py
> +    Please note: setting this to True is required for propagating traces to Lambda
👍

2021-07-15 16:10 UTC, agocs commented on ddtrace/contrib/botocore/__init__.py
> +    When a tracing a directly invoked lambda function, the trace context is added to the
👍

2021-07-19 14:35 UTC, Kyle-Verhoog reviewed
nice! just some last concerns about the release note but otherwise lgtm!

2021-07-19 14:35 UTC, Kyle-Verhoog commented on releasenotes/notes/botocore-46f5bf04f64777b4.yaml
> +features:
this should be an `upgrade`-level note mentioning the change and the backwards compatibility option as users using older python/node lambda client versions will have a breaking change

2021-07-19 14:35 UTC, Kyle-Verhoog commented on ddtrace/contrib/botocore/__init__.py
> +.. py:data:: ddtrace.config.botocore['invoke_with_legacy_context']
:+1: I think I'm good with this name.

@DataDog/apm-python thoughts?

2021-07-19 14:35 UTC, Kyle-Verhoog commented on releasenotes/notes/botocore-46f5bf04f64777b4.yaml
> +    botocore: added `invoke_with_legacy_context` configuration setting, which is disabled by default. This configuration setting is to preserve a legacy behavior in which, when tracing a direct lambd
I'd probably trim this down as well. From the user standpoint they just need to know that context management support has been added for newer lambda libraries and that there is a legacy configuration option in-case they wish to run an older version.

:+1: for mentioning the specific versions of each library.

Would also be good to explicitly show the configuration options, something like:

```
Legacy support for older libraries is available with ddtrace.config.botocore.invoke_with_legacy_context = True or by setting the environment variable DD_BOTOCORE_INVOKE_WITH_LEGACY_CONTEXT=true
```

2021-07-21 15:32 UTC, Kyle-Verhoog requested changes
Just one more thought on the release note!

2021-07-21 15:32 UTC, Kyle-Verhoog commented on releasenotes/notes/botocore-46f5bf04f64777b4.yaml
> +    botocore: added `invoke_with_legacy_context` configuration setting, which is disabled by default. This configuration setting is to preserve a legacy behavior in which, when tracing a direct lambd
I'd like to see it explicitly mentioned that the propagation will break for users using `datadog-lambda-python < v41 or datadog-lambda-js < v3.57.0` first and then mention the introduction of the legacy setting that can be used to support these older versions.

2021-07-21 21:52 UTC, brettlangdon approved these changes

2021-07-22 12:14 UTC, Kyle-Verhoog approved these changes
👏 thanks for bearing with my nitty documentation feedback @agocs!

2021-07-22 12:15 UTC, merged