Update linting, formatting commands
DataDog/dd-trace-py pull request #2643
Opened 2021-07-13 15:15 UTC by Kyle-Verhoog

Our linting and formatting commands were not considering new
directories like benchmarks/ which also contain python code which we
should lint and format.

2021-07-14 13:43 UTC, P403n1x87 requested changes
Is it possible to separate the changes to the configuration sources from the formatting?

2021-07-14 14:23 UTC, Kyle-Verhoog commented
Sure thing!

2021-07-14 14:36 UTC, Kyle-Verhoog commented
Pulled the lesser related riotfile changed into #2647

2021-07-14 15:08 UTC, brettlangdon approved these changes

2021-07-15 14:54 UTC, P403n1x87 approved these changes

2021-07-15 15:16 UTC, merged