perf: use non-forksafe RLock in context
DataDog/dd-trace-py pull request #3043
Opened 2021-12-02 16:45 UTC by brettlangdon

## Commit Message
{{title}}

Previously in #3036 we made a change to use a forksafe RLock
but did not re-measure the performance overhead of the change.

Creation of a `forksafe.RLock()` is 3 times slower than a
regular `threading.RLock`.

master   - Context(): Mean +- std dev: 3.24 us +- 0.34 us
v0.56.1  - Context(): Mean +- std dev: 754 ns +- 17 ns

Given that we do not _require_ a forksafe lock here we
should use a normal `threading.RLock` for performance reasons.

2021-12-02 17:56 UTC, majorgreys approved these changes

2021-12-02 19:54 UTC, Kyle-Verhoog requested changes
> Given that we do not require a forksafe lock here

Worth noting that we don't require a fork safe lock because the lock in the context objects are recreated on fork: https://github.com/DataDog/dd-trace-py/blob/a1932e8ddb704d259ea8a3188d30bf542f59fd8d/ddtrace/tracer.py#L489-L508 when starting a new span.

However, there is the possibility that a deadlock could occur still if a span from a parent process is used in a child and there is a competing thread that acquires the context lock when the fork occurs. In this case the context lock in the child will be permanently locked and if the user tries to update the sampling priority on the span (and context) from the parent process then a dead lock will occur.

Can we document that spans should only be used in the process in which they are created? Maybe in the Span docstring and in the context section: https://ddtrace.readthedocs.io/en/v0.56.1/advanced_usage.html#span

2021-12-02 23:57 UTC, brettlangdon commented
@Kyle-Verhoog I updated the docs here, let me know what you think.

2021-12-03 10:42 UTC, P403n1x87 commented
That's a shame 😞 . I wonder if we could profile the forksafe lock and see if we could do anything to improve its performance?

2021-12-03 13:52 UTC, brettlangdon commented
> That's a shame 😞 . I wonder if we could profile the forksafe lock and see if we could do anything to improve its performance?

We did a quick test on if the lock operations are also slowed down by about 2x. This is likely just showcasing the performance overhead from `wrapt.ObjectProxy`.

```
with threading.RLock(): Mean +- std dev: 326 ns +- 19 ns
with threading.Lock(): Mean +- std dev: 317 ns +- 28 ns
with forksafe.RLock(): Mean +- std dev: 619 ns +- 36 ns
with forksafe.Lock(): Mean +- std dev: 614 ns +- 34 n
```

<details>
<summary>Perf code</summary>

```python
import threading

import pyperf

from ddtrace.context import Context
from ddtrace.internal import forksafe


def add_args(args, cmd):
    cmd.rigorous = True


runner = pyperf.Runner(warmups=10, add_cmdline_args=add_args)


def run(lock):
    with lock:
        pass


runner.bench_func("with threading.RLock()", run, threading.RLock())
runner.bench_func("with threading.Lock()", run, threading.Lock())
runner.bench_func("with forksafe.RLock()", run, forksafe.RLock())
runner.bench_func("with forksafe.Lock()", run, forksafe.Lock())
```

</details>

2021-12-03 14:24 UTC, Kyle-Verhoog approved these changes
thanks!

2021-12-03 16:53 UTC, merged

2021-12-03 16:53 UTC, majorgreys approved these changes