Remove ddtrace.util.py
DataDog/dd-trace-py pull request #3058
Opened 2021-12-09 00:04 UTC by ZStriker19

## Commit Message
{{title}}

Removing ddtrace.util.py for 1.0. It's already been deprecated.

## Checklist
- [ ] Added to the correct milestone.
- [ ] Tests provided or description of manual testing performed is included in the code or PR.
- [ ] Library documentation is updated.
- [ ] [Corp site](https://github.com/DataDog/documentation/) documentation is updated (link to the PR).

2021-12-09 17:29 UTC, brettlangdon commented on releasenotes/notes/removed_ddtrace.util.py-0d0f48aefa6d9779.yaml
> +    Removed ``ddtrace/util.py``. Please use modules in ddtrace/utils instead.
```suggestion
    Removed ``ddtrace.util`` module. Please use ``ddtrace.utils`` instead.
```

? not sure.

2021-12-09 17:45 UTC, brettlangdon submitted a review, later dismissed

2021-12-09 22:21 UTC, mabdinur submitted a review, later dismissed

2021-12-09 22:24 UTC, Kyle-Verhoog requested changes

2021-12-09 22:24 UTC, Kyle-Verhoog commented on releasenotes/notes/removed_ddtrace.util.py-0d0f48aefa6d9779.yaml
> +    Removed ``ddtrace.util`` module. Please use ``ddtrace.utils`` instead.
We're getting rid of ddtrace.utils as well. We should just say it's being removed. No one should be using anything from here anymore anyway

2021-12-10 21:36 UTC, brettlangdon approved these changes

2021-12-10 21:37 UTC, Kyle-Verhoog submitted a review, later dismissed

2021-12-10 21:37 UTC, Kyle-Verhoog commented on docs/spelling_wordlist.txt
> +utils
Probably don't need this anymore

2021-12-10 21:37 UTC, brettlangdon commented on docs/spelling_wordlist.txt
> +utils
```suggestion
```

2021-12-10 21:38 UTC, brettlangdon approved these changes

2021-12-10 21:38 UTC, Kyle-Verhoog approved these changes

2021-12-13 15:46 UTC, merged