Move propagation.utils to trace utils
DataDog/dd-trace-py pull request #3065
Opened 2021-12-13 04:37 UTC by ZStriker19

## Commit Message
Moving propagation.utils to trace_utils

## Checklist
- [ ] Added to the correct milestone.
- [ ] Tests provided or description of manual testing performed is included in the code or PR.
- [ ] Library documentation is updated.
- [ ] [Corp site](https://github.com/DataDog/documentation/) documentation is updated (link to the PR).

2021-12-13 13:28 UTC, brettlangdon commented on releasenotes/notes/move_propagation.utils_to_trace_utils-6bdfed9fcb98a995.yaml
> +    The ``propagation.utils`` module has been removed. Public methods have been moved to ``trace_utils.py``
```suggestion
    The ``propagation.utils`` module has been removed. Public methods have been moved to ``ddtrace.contrib.trace_utils``
```

2021-12-13 13:29 UTC, brettlangdon commented on releasenotes/notes/move_propagation.utils_to_trace_utils-6bdfed9fcb98a995.yaml
> +    The ``propagation.utils`` module has been removed. Public methods have been moved to ``trace_utils.py``
we just want to state the module path that they were moved to, the file name won't help anyone.

2021-12-13 17:39 UTC, brettlangdon approved these changes

2021-12-13 17:39 UTC, brettlangdon requested changes
a bunch of tests are failing

2021-12-13 21:20 UTC, ZStriker19 commented
Waiting on this PR for the moment because @Kyle-Verhoog  brought up that perhaps we should just deprecate all of propagation and create a base class for propagation for users to implement.

2021-12-14 18:40 UTC, Kyle-Verhoog requested changes
We should do the deprecation PR first (targeting master) then update the 1.0-dev branch with master and then do this PR with the removal

2022-02-03 20:29 UTC, ZStriker19 commented
Syncing with Kyle: Do we need to actually re-expose these helpers publicly through `trace.utils`?

2022-02-10 15:39 UTC, majorgreys commented
Moved to https://github.com/DataDog/dd-trace-py/pull/3236

2022-02-10 15:39 UTC, closed without merging