refactor!: remove HTTPServerConfig from the public api [ddtrace-1.0]
DataDog/dd-trace-py pull request #3165
Opened 2022-01-24 17:28 UTC by mabdinur

Internalize HTTPServerConfig.

`ddtrace.config.http_server` should be used to set http server configurations.

## Checklist
- [ ] Added to the correct milestone.
- [ ] Tests provided or description of manual testing performed is included in the code or PR.
- [ ] Library documentation is updated.
- [ ] [Corp site](https://github.com/DataDog/documentation/) documentation is updated (link to the PR).

2022-01-25 10:41 UTC, P403n1x87 submitted a review, later dismissed

2022-01-25 19:14 UTC, brettlangdon reviewed
I wonder if we should wait for the rebase/merge from `master` with #3163, and then the only change is removing the already deprecated `HTTPServerConfig`.

Otherwise we are going to have a merge conflict here.

2022-01-25 19:23 UTC, mabdinur commented
> I wonder if we should wait for the rebase/merge from `master` with #3163, and then the only change is removing the already deprecated `HTTPServerConfig`.
> 
> Otherwise we are going to have a merge conflict here.

Yup, my plan is to merge all the deprecation warnings into master first (probably in batches of 2-3 PRs), rebase 1.0-dev and then merge the 1.0-dev changes

2022-02-01 20:36 UTC, brettlangdon requested changes
Since rebasing on `master` there are no changes in this PR anymore.

2022-02-01 20:58 UTC, brettlangdon commented on releasenotes/notes/internalize_http_server-06721b67e63dde1d.yaml
> +    HTTPServerConfig was removed from the public api
```suggestion
    ``ddtrace.settings.HTTPServerConfig`` was removed from the public api.
```

2022-02-01 20:59 UTC, brettlangdon reviewed
last nit, then lgtm

2022-02-01 21:14 UTC, brettlangdon submitted a review, later dismissed

2022-02-02 01:55 UTC, Kyle-Verhoog commented on releasenotes/notes/internalize_http_server-06721b67e63dde1d.yaml
> +    ``ddtrace.settings.HTTPServerConfig`` was removed from the public api.
```suggestion
    ``ddtrace.settings.Config.HTTPServerConfig`` was removed from the public api.
```

2022-02-02 16:03 UTC, Kyle-Verhoog approved these changes

2022-02-02 16:31 UTC, brettlangdon approved these changes

2022-02-03 18:08 UTC, merged