fix(logging): fix service in log correlation
DataDog/dd-trace-py pull request #3267
Opened 2022-02-15 12:54 UTC by sileht

# Feature

The service reported in logs can be wrong if set in the span itself.

## Checklist
- [ ] Added to the correct milestone.
- [ ] Library documentation is updated.
- [ ] [Corp site](https://github.com/DataDog/documentation/) documentation is updated (link to the PR).

### Testing
- [ ] Tests are run against all relevant library versions (or confirm that the relevant versions are already being tested in `tox.ini`)

2022-02-15 13:02 UTC, jd requested changes
LGTM since this implements the same logic we have in `start_span`.
However, I think you can simplify a bit the condition to find the service.

2022-02-15 13:02 UTC, jd commented on ddtrace/tracer.py
> +            service = span.service
```suggestion
        if span and span.service:
            service = span.service
        else:
            service = config.service
```

2022-02-15 13:12 UTC, brettlangdon reviewed
hey @sileht would you be able to add a release note as well:

```
pip install -U reno
reno new <some-short-note-slug>
```

This would be a `fixes:` note.

2022-02-15 15:25 UTC, Kyle-Verhoog approved these changes

2022-02-18 01:23 UTC, mabdinur submitted a review, later dismissed

2022-02-18 13:38 UTC, majorgreys commented
@mergifyio backport 0.58

2022-02-18 13:40 UTC, brettlangdon approved these changes

2022-02-18 13:59 UTC, majorgreys commented on ddtrace/tracer.py
> +            "service": service,
We want to retain an empty string as the default as we do for `version` and `env`:

```suggestion
            "service": service or "",
```

2022-02-18 14:05 UTC, majorgreys submitted a review, later dismissed

2022-02-18 14:05 UTC, brettlangdon submitted a review, later dismissed

2022-02-18 17:37 UTC, mabdinur approved these changes

2022-02-18 17:38 UTC, brettlangdon approved these changes

2022-02-18 18:03 UTC, merged