adding starlette and fastapi patch testing
DataDog/dd-trace-py pull request #3631
Opened 2022-04-25 22:24 UTC by ZStriker19

In preparation for https://github.com/DataDog/dd-trace-py/pull/3612 since in that PR Starlette patching is added to Fastapi patching.

## Checklist
- [ ] Added to the correct milestone.
- [ ] Tests provided or description of manual testing performed is included in the code or PR.
- [ ] Library documentation is updated.
- [ ] [Corp site](https://github.com/DataDog/documentation/) documentation is updated (link to the PR).

2022-04-25 23:01 UTC, brettlangdon commented on tests/contrib/fastapi/test_fastapi_patch.py
> +        self.assert_wrapped(fastapi.__init__)
```suggestion
        self.assert_not_wrapped(fastapi.__init__)
```

2022-04-25 23:01 UTC, brettlangdon commented on tests/contrib/fastapi/test_fastapi_patch.py
> +        self.assert_wrapped(fastapi.__init__)
```suggestion
        self.assert_not_double_wrapped(fastapi.__init__)
```

2022-04-25 23:01 UTC, brettlangdon commented on tests/contrib/fastapi/test_fastapi_patch.py
> +from ddtrace.contrib.fastapi import patch
```suggestion
from ddtrace.contrib.fastapi import patch, unpatch
```

2022-04-25 23:01 UTC, brettlangdon commented on tests/contrib/fastapi/test_fastapi_patch.py
> +    __unpatch_func__ = None
```suggestion
    __unpatch_func__ = unpatch
```

2022-04-25 23:01 UTC, brettlangdon commented on tests/contrib/starlette/test_starlette_patch.py
> +class TestStarlettePatch(PatchTestCase.Base):
same comments apply here

2022-04-26 13:20 UTC, P403n1x87 submitted a review, later dismissed

2022-04-26 13:38 UTC, brettlangdon submitted a review, later dismissed

2022-04-26 13:49 UTC, brettlangdon commented on tests/contrib/fastapi/test_fastapi_patch.py
> +from ddtrace.contrib.fastapi import patch, unpatch
```suggestion
from ddtrace.contrib.fastapi import patch
from ddtrace.contrib.fastapi import unpatch
```

2022-04-27 14:14 UTC, mabdinur approved these changes

2022-04-28 16:56 UTC, Kyle-Verhoog reviewed
@ZStriker19 looks like the fastapi tests are failing

2022-05-03 15:55 UTC, P403n1x87 approved these changes

2022-05-19 14:02 UTC, brettlangdon commented on tests/contrib/patch.py
> +
No longer needed, can we delete?

2022-05-19 14:31 UTC, brettlangdon approved these changes

2022-05-19 14:33 UTC, brettlangdon requested changes

2022-05-19 14:33 UTC, brettlangdon commented on tests/contrib/fastapi/test_fastapi_patch.py
> +        self.assert_wrapped(fastapi.applications.FastAPI.__init__)
We are missing testing for `serialize_response`.

https://github.com/DataDog/dd-trace-py/blob/1595f9f9d/ddtrace/contrib/fastapi/patch.py#L72-L72

2022-05-19 14:47 UTC, brettlangdon approved these changes

2022-05-20 09:55 UTC, Kyle-Verhoog approved these changes

2022-05-20 09:56 UTC, merged