refactor: extract reusable logic from Agent Writer to HTTP Writer
DataDog/dd-trace-py pull request #3690
Opened 2022-05-09 10:16 UTC by jirikuncar

This is preparing ground for CI Visibility Agentless support that will reuse retry logic from Agent Writer. Also we would like to keep the possibility for metrics calculation and submission in background.

https://github.com/DataDog/dd-trace-py/pull/3654#discussion_r866849329

## Checklist
- [ ] Added to the correct milestone.
- [ ] Tests provided or description of manual testing performed is included in the code or PR.
- [ ] Library documentation is updated.
- [ ] [Corp site](https://github.com/DataDog/documentation/) documentation is updated (link to the PR).

2022-05-17 09:41 UTC, majorgreys commented on ddtrace/internal/writer.py
>              max_size=self._buffer_size,
We discussed moving these encoder parameters out of the writer in a separate refactor.

2022-05-17 09:41 UTC, majorgreys commented on ddtrace/internal/writer.py
This should be specified so subclasses need to implement.

2022-05-17 09:41 UTC, majorgreys commented on ddtrace/internal/writer.py
>                  if t >= self.interval:
We should be emitting this timing as a metric as well.

2022-05-17 09:41 UTC, majorgreys commented on releasenotes/notes/HTTP-Writer-7bd3c1bd0234cd2d.yaml
> +---
We can drop this release note as the refactor is only to internal api.

2022-05-17 09:44 UTC, Kyle-Verhoog commented on releasenotes/notes/HTTP-Writer-7bd3c1bd0234cd2d.yaml
> +    Refactors the Agent Writer to use the new HTTP Writer interface.
```suggestion
```

this is an internal refactor

2022-05-17 09:44 UTC, Kyle-Verhoog commented on ddtrace/internal/writer.py
> -            "Datadog-Client-Computed-Top-Level": "yes",
Merge conflict?

2022-05-17 09:44 UTC, Kyle-Verhoog commented on ddtrace/internal/writer.py
> +        # TODO (jirikuncar): define encoder protocol
```suggestion
```

2022-07-05 20:13 UTC, Kyle-Verhoog requested changes
I'm not a huge fan of this refactor as it is but I think it's a step in the right direction. There's too much coupling to the specific data model used by /v0.3/v0.4/v0.5 traces which we're just splitting into two classes. The parent class `HTTPWriter` still has dependence on the same logic and contains agent specific logic.

If reusability is the objective then I think a "has-a" relationship would be better than a "is-a". That is, encapsulate the transmission state and the corresponding metrics into its own class and have writers maintain an instance of that class.

This PR did separate a bit of the logic, I think we just need to pull out the last bits of agent-specific code and change the class relationship.

2022-12-19 18:18 UTC, closed without merging

2023-04-04 21:46 UTC, emmettbutler commented
@Kyle-Verhoog I'm working on a fresh attempt at this change [here](https://github.com/DataDog/dd-trace-py/compare/1.x...emmett.butler/civ-agentless), and I'm not sure I can see the need for the "has-a" relationship you described here. I think I've got a change that pretty well separates the concerns that are AgentWriter-specific from those that apply to the HTTPWriter using an "is-a" relationship. I'm not asking you to review that change, but could you provide any more detail on what "transmission state and corresponding metrics" would be better encapsulated in an instance attribute than a subclass relationship? Thanks a lot for loading this old comment back into your brain.

2023-04-05 19:38 UTC, Kyle-Verhoog commented
@emmettbutler I think where I was coming from is the leaking of concerns between the base and subclasses. By doing an "is-a" relationship it is very easy to move a method up a layer of the classes and have the concerns leaked to the base. 

I think "is-a" can work it's just much easier to fall into implicitly coupling the classes because it's so easy to share state between them.