test(profiling): reduce flaky tests probability
DataDog/dd-trace-py pull request #3921
Opened 2022-07-07 13:14 UTC by jd

This waits for events to happen, which should limit the possibility for a test
failure as we've seen from time to time in the CI.

```
    @pytest.mark.skipif(not stack.FEATURES["stack-exceptions"], reason="Stack exceptions not supported")
    def test_exception_collection_trace(tracer):
        r = recorder.Recorder()
        c = stack.StackCollector(r, tracer=tracer)
        with c:
            with tracer.trace("test123") as span:
                try:
                    raise ValueError("hello")
                except Exception:
                    nogevent.sleep(1)

        exception_events = r.events[stack_event.StackExceptionSampleEvent]
>       assert len(exception_events) >= 1
E       assert 0 >= 1
E        +  where 0 = len(deque([]))
```

2022-07-07 13:23 UTC, majorgreys commented on tests/profiling/collector/test_stack.py
> +                exception_events = r.reset()[stack_event.StackExceptionSampleEvent]
I like numbers greater than 1, just like the next person.

I think 3 is a good "flaky" threshold:

https://github.com/DataDog/dd-trace-py/blob/6f61c52bf40d8471de17996f080a60a548b48ee3/scripts/ddtest#L12-L13

2022-07-07 16:22 UTC, ZStriker19 submitted a review, later dismissed

2022-07-07 16:52 UTC, brettlangdon requested changes

2022-07-12 12:35 UTC, jd commented on tests/profiling/collector/test_stack.py
> +                exception_events = r.reset()[stack_event.StackExceptionSampleEvent]
done

2022-07-12 12:49 UTC, P403n1x87 approved these changes

2022-07-12 13:03 UTC, brettlangdon approved these changes

2022-07-12 13:25 UTC, merged