fix(telemetry): avoid starting the telemetry after a process forks
DataDog/dd-trace-py pull request #3984
Opened 2022-07-25 19:52 UTC by mabdinur

The telemetry writer is still running after a fork. Calling `writer.start()` on a live periodic service raises an Exception. 

## Description

## Checklist
- [ ] Title must conform to [conventional commit](https://github.com/conventional-changelog/commitlint/tree/master/%40commitlint/config-conventional).
- [ ] Add additional sections for `feat` and `fix` pull requests.
- [ ] Ensure tests are passing for affected code.
- [ ] [Library documentation](https://github.com/DataDog/dd-trace-py/tree/1.x/docs) and/or [Datadog's documentation site](https://github.com/DataDog/documentation/) is updated. Link to doc PR in description.

## Motivation

## Design 

## Testing strategy

## Relevant issue(s)

## Testing strategy

## Reviewer Checklist
- [ ] Title is accurate.
- [ ] Description motivates each change.
- [ ] No unnecessary changes were introduced in this PR.
- [ ] PR cannot be broken up into smaller PRs.
- [ ] Avoid breaking [API](https://ddtrace.readthedocs.io/en/stable/versioning.html#interfaces) changes unless absolutely necessary.
- [ ] Tests provided or description of manual testing performed is included in the code or PR.
- [ ] Release note has been added for fixes and features, or else `changelog/no-changelog` label added.
- [ ] All relevant GitHub issues are correctly linked.
- [ ] Backports are identified and tagged with Mergifyio.
- [ ] Add to milestone.

2022-07-25 20:44 UTC, mabdinur commented
@Mergifyio backport 1.2 1.3

2022-07-25 22:02 UTC, ZStriker19 submitted a review, later dismissed

2022-07-26 01:09 UTC, mabdinur commented
Regression tests will be added in the following PR: https://github.com/DataDog/dd-trace-py/pull/3982

2022-07-26 09:35 UTC, P403n1x87 commented
Is the telemetry writer supposed to run only in the main process? If so, perhaps the fork hook could do some clean-up and remove any references to the writer in the child processes?

2022-07-26 14:43 UTC, majorgreys submitted a review, later dismissed

2022-07-26 17:35 UTC, Kyle-Verhoog requested changes
Let's add a regression test case using the repro steps that you have and then this is good to go 👍

2022-07-26 18:52 UTC, mabdinur commented on tests/tracer/telemetry/test_telemetry.py
> +def test_fork(ddtrace_run_python_code_in_subprocess):
This test will be updated in the following PR to ensure the correct payloads are sent when a process forks: https://github.com/DataDog/dd-trace-py/pull/3982

2022-07-26 20:09 UTC, ZStriker19 approved these changes

2022-07-26 20:48 UTC, Kyle-Verhoog approved these changes

2022-07-26 20:49 UTC, merged

2022-07-26 20:53 UTC, mabdinur commented
@Mergifyio refresh

2022-07-27 13:16 UTC, mabdinur commented
@Mergifyio backport 1.2 1.3