chore(telemetry): move telemetry tests
DataDog/dd-trace-py pull request #4016
Opened 2022-07-29 19:55 UTC by mabdinur

## Description

Blocks: https://github.com/DataDog/dd-trace-py/pull/3982

We would like to use the test agent to validate telemetry events and this not possible without either refactoring existing tracer tests ([failing tracer tests when the test agent is used](https://app.circleci.com/pipelines/github/DataDog/dd-trace-py/19468/workflows/cc418d1f-35f4-4de4-9ab0-ed2e687f75b6/jobs/1315764) or running telemetry tests outside of the existing tracer test suite. 

This PR takes the second approach.

## Checklist
- [ ] Title must conform to [conventional commit](https://github.com/conventional-changelog/commitlint/tree/master/%40commitlint/config-conventional).
- [ ] Add additional sections for `feat` and `fix` pull requests.
- [ ] Ensure tests are passing for affected code.
- [ ] [Library documentation](https://github.com/DataDog/dd-trace-py/tree/1.x/docs) and/or [Datadog's documentation site](https://github.com/DataDog/documentation/) is updated. Link to doc PR in description.

## Motivation

## Design 

## Testing strategy

## Relevant issue(s)

## Testing strategy

## Reviewer Checklist
- [ ] Title is accurate.
- [ ] Description motivates each change.
- [ ] No unnecessary changes were introduced in this PR.
- [ ] PR cannot be broken up into smaller PRs.
- [ ] Avoid breaking [API](https://ddtrace.readthedocs.io/en/stable/versioning.html#interfaces) changes unless absolutely necessary.
- [ ] Tests provided or description of manual testing performed is included in the code or PR.
- [ ] Release note has been added for fixes and features, or else `changelog/no-changelog` label added.
- [ ] All relevant GitHub issues are correctly linked.
- [ ] Backports are identified and tagged with Mergifyio.
- [ ] Add to milestone.

2022-08-01 15:02 UTC, Kyle-Verhoog approved these changes

2022-08-01 18:25 UTC, brettlangdon requested changes

2022-08-01 18:25 UTC, brettlangdon commented on .circleci/config.yml
> +          pattern: "telemtry"
```suggestion
          pattern: "telemetry"
```

2022-08-02 15:39 UTC, Kyle-Verhoog approved these changes

2022-08-02 18:35 UTC, ZStriker19 approved these changes

2022-08-02 19:33 UTC, brettlangdon approved these changes

2022-08-02 20:14 UTC, merged