ci(system-tests): add python integration unit tests to ci
DataDog/dd-trace-py pull request #4184
Opened 2022-09-12 17:54 UTC by mabdinur

## Description

## Checklist
- [ ] Title must conform to [conventional commit](https://github.com/conventional-changelog/commitlint/tree/master/%40commitlint/config-conventional).
- [ ] Add additional sections for `feat` and `fix` pull requests.
- [ ] Ensure tests are passing for affected code.
- [ ] [Library documentation](https://github.com/DataDog/dd-trace-py/tree/1.x/docs) and/or [Datadog's documentation site](https://github.com/DataDog/documentation/) is updated. Link to doc PR in description.

## Motivation

## Design 

## Testing strategy

## Relevant issue(s)

## Testing strategy

## Reviewer Checklist
- [ ] Title is accurate.
- [ ] Description motivates each change.
- [ ] No unnecessary changes were introduced in this PR.
- [ ] PR cannot be broken up into smaller PRs.
- [ ] Avoid breaking [API](https://ddtrace.readthedocs.io/en/stable/versioning.html#interfaces) changes unless absolutely necessary.
- [ ] Tests provided or description of manual testing performed is included in the code or PR.
- [ ] Release note has been added for fixes and features, or else `changelog/no-changelog` label added.
- [ ] All relevant GitHub issues are correctly linked.
- [ ] Backports are identified and tagged with Mergifyio.
- [ ] Add to milestone.

2022-09-12 18:02 UTC, mabdinur commented on .github/workflows/system-tests.yml
> +          ref: 'apm-test-client'
TO DO:
```suggestion
```

2022-09-16 19:23 UTC, Kyle-Verhoog requested changes

2022-09-16 19:24 UTC, Kyle-Verhoog commented on .github/workflows/system-tests.yml
> +  integration_unit:
```suggestion
  parametric:
```

2022-09-16 19:25 UTC, Kyle-Verhoog submitted a review, later dismissed

2022-09-16 20:07 UTC, Yun-Kim approved these changes

2022-09-16 20:22 UTC, Kyle-Verhoog approved these changes

2022-09-16 20:51 UTC, merged