chore(perrformance): replace set_tag by set_str_tag
DataDog/dd-trace-py pull request #4222
Opened 2022-09-22 10:00 UTC by avara1986

## Description
Replace `set_tag` by `set_str_tag`
Rename `_set_str_tag` to `set_str_tag` (It's a public method)

## Reviewer Checklist
- [ ] Title is accurate.
- [ ] Description motivates each change.
- [ ] No unnecessary changes were introduced in this PR.
- [ ] PR cannot be broken up into smaller PRs.
- [ ] Avoid breaking [API](https://ddtrace.readthedocs.io/en/stable/versioning.html#interfaces) changes unless absolutely necessary.
- [ ] Tests provided or description of manual testing performed is included in the code or PR.
- [ ] Release note has been added for fixes and features, or else `changelog/no-changelog` label added.
- [ ] All relevant GitHub issues are correctly linked.
- [ ] Backports are identified and tagged with Mergifyio.
- [ ] Add to milestone.

2022-09-22 14:13 UTC, Kyle-Verhoog reviewed
I'm good with making the method public, what's the motivation behind the change? Can we add it to the PR description?

2022-09-22 14:13 UTC, Kyle-Verhoog commented on ddtrace/span.py
> +    def set_str_tag(self, key, value):
```suggestion
    def set_tag_str(self, key, value):
```

maybe is a little better since we're changing it 😄

2022-09-22 15:33 UTC, Kyle-Verhoog approved these changes

2022-09-22 15:48 UTC, gnufede submitted a review, later dismissed

2022-09-22 15:49 UTC, juanjux submitted a review, later dismissed

2022-09-22 16:05 UTC, majorgreys requested changes
Can we keep the internal api as it is and use `_set_str_tag`? We can then backport for patch releases. The feature PR to make the internal interface public would be done as a follow up.

2022-09-23 16:37 UTC, gnufede submitted a review, later dismissed

2022-09-26 13:39 UTC, majorgreys commented
Thanks @avara1986!

This is a non-breaking feature change to the public interface. Can you update the PR title to reflect that and add a release note?

2022-09-29 07:34 UTC, juanjux submitted a review, later dismissed

2022-09-29 09:55 UTC, gnufede approved these changes

2022-09-29 13:21 UTC, majorgreys requested changes
Release notes updated to reflect change to public API.

2022-09-29 13:21 UTC, majorgreys commented on releasenotes/notes/span-_set_str_tag-is-replaced-by-span-set_tag_str-271b7829efd9e6ac.yaml
> +upgrade:
```suggestion
feature:
```

2022-09-29 13:21 UTC, majorgreys commented on releasenotes/notes/span-_set_str_tag-is-replaced-by-span-set_tag_str-271b7829efd9e6ac.yaml
> +    ``Span._set_str_tag()`` is replaced by ``Span.set_tag_str()``.
```suggestion
    Add ``Span.set_tag_str()`` as an alternative to the overloaded functionality of ``Span.set_tag()` when the value can be coerced to unicode text. This function can be used for performance optimizations in manual instrumentation.
```

2022-09-29 14:01 UTC, majorgreys submitted a review, later dismissed

2022-09-29 14:22 UTC, gnufede approved these changes

2022-09-29 14:47 UTC, juanjux approved these changes

2022-09-29 18:38 UTC, merged