chore(sqlcommenter): vendor file to format sql comments in dbm-apm link
DataDog/dd-trace-py pull request #4310
Opened 2022-10-12 20:58 UTC by mabdinur

## Description

The vendored function `ddtrace.vendor.sqlcommeneter.generate_sql_comment(**tracer_tags)` will be used to generate and then prepend trace data to SQL queries. This will be used by the Database Monitoring Product.

## Checklist
- [ ] Title must conform to [conventional commit](https://github.com/conventional-changelog/commitlint/tree/master/%40commitlint/config-conventional).
- [ ] Add additional sections for `feat` and `fix` pull requests.
- [ ] Ensure tests are passing for affected code.
- [ ] [Library documentation](https://github.com/DataDog/dd-trace-py/tree/1.x/docs) and/or [Datadog's documentation site](https://github.com/DataDog/documentation/) is updated. Link to doc PR in description.

## Motivation

## Design 

## Testing strategy

## Relevant issue(s)

## Testing strategy

## Reviewer Checklist
- [ ] Title is accurate.
- [ ] Description motivates each change.
- [ ] No unnecessary changes were introduced in this PR.
- [ ] PR cannot be broken up into smaller PRs.
- [ ] Avoid breaking [API](https://ddtrace.readthedocs.io/en/stable/versioning.html#interfaces) changes unless absolutely necessary.
- [ ] Tests provided or description of manual testing performed is included in the code or PR.
- [ ] Release note has been added for fixes and features, or else `changelog/no-changelog` label added.
- [ ] All relevant GitHub issues are correctly linked.
- [ ] Backports are identified and tagged with Mergifyio.
- [ ] Add to milestone.

2022-10-13 14:21 UTC, ZStriker19 approved these changes

2022-10-13 14:25 UTC, majorgreys requested changes
Move vendored message to https://github.com/DataDog/dd-trace-py/blob/edab3ebd445d961891a4a0432c21fbc48a14405f/ddtrace/vendor/__init__.py

2022-10-13 14:27 UTC, majorgreys commented
Not a blocker but I would suggest we keep the directory structure of the vendored library as-is but remove any files we do not intend to use.

2022-10-13 17:37 UTC, mabdinur commented on ddtrace/vendor/__init__.py
> +base.log = get_logger("ddtrace.vendor.dogstatsd")
```suggestion
base.log = get_logger('ddtrace.vendor.dogstatsd')
```

2022-10-14 13:37 UTC, majorgreys approved these changes

2022-10-14 13:46 UTC, ZStriker19 approved these changes

2022-10-14 15:30 UTC, merged