chore(flask): avoid using deprecated internals
DataDog/dd-trace-py pull request #4433
Opened 2022-10-31 21:42 UTC by mabdinur

## Description

The following flask attributes have been deprecated in flask v2.2.2 and will be removed in the next minor release:
- [flask. _app_ctx_stack](https://github.com/pallets/flask/blob/2a54cfa5cecf4dd9f17525bf3ebae4d33a155776/src/flask/__init__.py#L58) 
- [flask. _request_ctx_stack](https://github.com/pallets/flask/blob/2a54cfa5cecf4dd9f17525bf3ebae4d33a155776/src/flask/__init__.py#L69)

This change replaces deprecated methods with flask globals (flask.current_app and flask.request). 

## Checklist
- [ ] Add additional sections for `feat` and `fix` pull requests.
- [ ] [Library documentation](https://github.com/DataDog/dd-trace-py/tree/1.x/docs) and/or [Datadog's documentation site](https://github.com/DataDog/documentation/) is updated. Link to doc PR in description.

## Relevant issue(s)
Closes: https://github.com/DataDog/dd-trace-py/issues/4430

## Testing strategy
Ensure existing flask tests pass

## Reviewer Checklist
- [ ] Title is accurate.
- [ ] Description motivates each change.
- [ ] No unnecessary changes were introduced in this PR.
- [ ] Avoid breaking [API](https://ddtrace.readthedocs.io/en/stable/versioning.html#interfaces) changes unless absolutely necessary.
- [ ] Tests provided or description of manual testing performed is included in the code or PR.
- [ ] Release note has been added for fixes and features, or else `changelog/no-changelog` label added.
- [ ] All relevant GitHub issues are correctly linked.
- [ ] Backports are identified and tagged with Mergifyio.

2022-10-31 21:48 UTC, Kyle-Verhoog approved these changes
happy to see `LocalStack` go 

lgtm given that this works for older flask versions as well (which our tests should verify)

2022-10-31 21:49 UTC, Kyle-Verhoog requested changes
we should have a release note here in case someone on an older version has issues. If so then when searching our release notes they'll see that the issue has been addressed in a newer version.

2022-10-31 23:52 UTC, Kyle-Verhoog commented on releasenotes/notes/remove-deprecated-flask-methods-8d7a4a3d32c3c69d.yaml
> +    flask: ``flask._app_ctx_stack`` and ``flask._request_ctx_stack`` were deprecated in flask v2.2.2. These attributes were removed from flask integration.
```suggestion
    flask: remove deprecated usages of ``flask._app_ctx_stack`` and ``flask._request_ctx_stack``.
```

2022-11-01 00:21 UTC, mabdinur commented on releasenotes/notes/remove-deprecated-flask-methods-8d7a4a3d32c3c69d.yaml
> +    flask: add support for flask v2.3. Remove the following deprecated attributes: ``flask._app_ctx_stack`` and ``flask._request_ctx_stack``.
```suggestion
    flask: add support for flask v2.3. Remove deprecated usages of ``flask._app_ctx_stack`` and ``flask._request_ctx_stack``.
```

2022-11-01 14:41 UTC, brettlangdon approved these changes

2022-11-01 15:00 UTC, mabdinur commented
@Mergifyio backport 1.6 1.5

2022-11-01 16:34 UTC, Kyle-Verhoog approved these changes

2022-11-01 16:45 UTC, merged