chore(opentracing): replace set_tag usages with set_tag_str
DataDog/dd-trace-py pull request #4705
Opened 2022-12-01 22:27 UTC by Yun-Kim

## Description
Replacing usages of set_tag() that are known to work only with text arguments to set_tag_str() in opentracing. This should provide a performance benefit as set_tag_str() bypasses the unnecessary type checking that occurs in set_tag().

## Checklist
- [ ] Followed the [library release note guidelines](https://ddtrace.readthedocs.io/en/stable/contributing.html#Release-Note-Guidelines) when writing a release note.
- [ ] Add additional sections for `feat` and `fix` pull requests.
- [ ] [Library documentation](https://github.com/DataDog/dd-trace-py/tree/1.x/docs) and/or [Datadog's documentation site](https://github.com/DataDog/documentation/) is updated. Link to doc PR in description.

## Motivation

## Design 

## Testing strategy

## Relevant issue(s)

## Testing strategy

## Reviewer Checklist
- [ ] Title is accurate.
- [ ] Description motivates each change.
- [ ] No unnecessary changes were introduced in this PR.
- [ ] Avoid breaking [API](https://ddtrace.readthedocs.io/en/stable/versioning.html#interfaces) changes unless absolutely necessary.
- [ ] Tests provided or description of manual testing performed is included in the code or PR.
- [ ] Release note has been added and follows the [library release note guidelines](https://ddtrace.readthedocs.io/en/stable/contributing.html#Release-Note-Guidelines), or else `changelog/no-changelog` label added.
- [ ] All relevant GitHub issues are correctly linked.
- [ ] Backports are identified and tagged with Mergifyio.

2022-12-02 18:47 UTC, Kyle-Verhoog commented
@Yun-Kim tests are failing here

2022-12-02 19:12 UTC, mabdinur requested changes

2022-12-02 19:12 UTC, mabdinur commented on ddtrace/opentracer/span.py
> +                self.set_tag_str(ERROR_TYPE, val)
I don't think we need to update the set_tag attribute on opentracing spans. We should only convert `self. _dd_span.set_tag()` to `self. _dd_span.set_tag_str()`

2022-12-06 15:44 UTC, Kyle-Verhoog approved these changes

2022-12-06 15:48 UTC, merged