feat(rcm): add more validations to Remote Config response from agent [backport #4970 to 1.7]
DataDog/dd-trace-py pull request #4973
Opened 2023-01-26 17:01 UTC by avara1986

## Description
Backport of #4970

Add more validations to Remote Config response from agent

2023-01-26 17:05 UTC, juanjux submitted a review, later dismissed

2023-01-26 17:18 UTC, gnufede submitted a review, later dismissed

2023-01-26 20:44 UTC, brettlangdon requested changes

2023-01-26 20:44 UTC, brettlangdon commented on releasenotes/notes/rcm-validations-162716c50ea90f1b.yaml
> +    Add more validations to Remote Config response from agent.
since this is a feature, it should not be backported.

2023-01-27 12:47 UTC, juanjux submitted a review, later dismissed

2023-01-28 15:17 UTC, brettlangdon approved these changes

2023-01-30 14:04 UTC, gnufede approved these changes

2023-02-02 15:16 UTC, mabdinur approved these changes

2023-02-03 09:12 UTC, merged