chore(graphene,graphql): add Python 3.11 testing for graphene/graphql tests
DataDog/dd-trace-py pull request #5037
Opened 2023-02-03 15:50 UTC by Yun-Kim

## Checklist
Blocked by #4854.

This change adds Python 3.11 testing to our graphql and graphene test suites.

- [ ] Change(s) are motivated and described in the PR description.
- [ ] Testing strategy is described if automated tests are not included in the PR.
- [ ] Risk is outlined (performance impact, potential for breakage, maintainability, etc).
- [ ] Change is maintainable (easy to change, telemetry, documentation).
- [ ] [Library release note guidelines](https://ddtrace.readthedocs.io/en/stable/contributing.html#Release-Note-Guidelines) are followed.
- [ ] Documentation is included (in-code, generated user docs, [public corp docs](https://github.com/DataDog/documentation/)).

## Reviewer Checklist

- [ ] Title is accurate.
- [ ] No unnecessary changes are introduced.
- [ ] Description motivates each change.
- [ ] Avoids breaking [API](https://ddtrace.readthedocs.io/en/stable/versioning.html#interfaces) changes unless absolutely necessary.
- [ ] Testing strategy adequately addresses listed risk(s).
- [ ] Change is maintainable (easy to change, telemetry, documentation).
- [ ] Release note makes sense to a user of the library.

2023-02-03 15:57 UTC, P403n1x87 commented on riotfile.py
> +                    pys=select_pys(min_version="3.6", max_version="3.11"),
```suggestion
                    pys=select_pys(min_version="3.6"),
```
?

2023-02-03 15:57 UTC, P403n1x87 commented on riotfile.py
> +                    pys=select_pys(min_version="3.6", max_version="3.11"),
```suggestion
                    pys=select_pys(min_version="3.6"),
```
?

2023-02-03 15:58 UTC, Yun-Kim commented on riotfile.py
> +                    pys=select_pys(min_version="3.6", max_version="3.11"),
Brain fart 🤦

2023-02-03 15:58 UTC, Yun-Kim commented on riotfile.py
> +                    pys=select_pys(min_version="3.6", max_version="3.11"),
Brain fart 🤦

2023-02-06 15:53 UTC, emmettbutler submitted a review, later dismissed

2023-02-06 17:26 UTC, mabdinur requested changes
Can we add a release note?

2023-02-06 18:33 UTC, Yun-Kim commented
> Can we add a release note?

After internal discussion, doesn't look like we'll need to add a release note since we never said in a previous release note we didn't support 3.11 for graphql/graphene.

2023-02-06 19:51 UTC, brettlangdon approved these changes
we could have included both notes in one release note file.

2023-02-06 19:55 UTC, mabdinur approved these changes

2023-02-06 19:55 UTC, mabdinur commented on releasenotes/notes/feat-graphql-py-3-11-5431bd3eedb38c50.yaml
> +    graphql: Adds support for Python 3.11.
```suggestion
    graphql: Adds support for Python 3.11.
  - |
    graphene: Adds support for Python 3.11.
```

2023-02-06 19:58 UTC, brettlangdon approved these changes

2023-02-06 20:15 UTC, merged