feat(tracing): add `db.system` tag to postgres-specific integrations
DataDog/dd-trace-py pull request #5080
Opened 2023-02-08 15:11 UTC by jbertran

## Description

Part of the effort to unify tag names across integrations and languages involve setting the `db.system` tag when tracing DB and KV store integrations.

This PR sets the tag on all postgres-specific integrations:
* `psycopg`
* `aiopg`
* `asyncpg`

All integration tests that check tags now _also_ check for the `db.system` tag. Those that did not (because the integration tested inherits its behaviour from another) have no test changes.

All relevant snapshots are updated with the addition of the new expected tag.

## Checklist

- [x] Change(s) are motivated and described in the PR description.
- [x] Testing strategy is described if automated tests are not included in the PR.
- [x] Risk is outlined (performance impact, potential for breakage, maintainability, etc).
- [x] Change is maintainable (easy to change, telemetry, documentation).
- [x] [Library release note guidelines](https://ddtrace.readthedocs.io/en/stable/contributing.html#Release-Note-Guidelines) are followed.
- [x] Documentation is included (in-code, generated user docs, [public corp docs](https://github.com/DataDog/documentation/)).

## Reviewer Checklist

- [ ] Title is accurate.
- [ ] No unnecessary changes are introduced.
- [ ] Description motivates each change.
- [ ] Avoids breaking [API](https://ddtrace.readthedocs.io/en/stable/versioning.html#interfaces) changes unless absolutely necessary.
- [ ] Testing strategy adequately addresses listed risk(s).
- [ ] Change is maintainable (easy to change, telemetry, documentation).
- [ ] Release note makes sense to a user of the library.

2023-02-08 19:13 UTC, emmettbutler approved these changes

2023-02-09 22:18 UTC, Yun-Kim requested changes

2023-02-09 22:18 UTC, Yun-Kim commented on releasenotes/notes/add-db-system-tag-pg-b4b6b8887f15fae6.yaml
> +    asyncpg.
```suggestion
    Adds the ``db.system`` tag to the following integrations: aiopg, psycopg, asyncpg.
```

2023-02-10 15:23 UTC, Yun-Kim submitted a review, later dismissed

2023-02-16 18:31 UTC, ZStriker19 approved these changes

2023-02-17 00:40 UTC, mabdinur approved these changes

2023-02-22 18:35 UTC, emmettbutler approved these changes

2023-02-23 15:30 UTC, merged