Adds `out.host` tag for celery and updates tests
DataDog/dd-trace-py pull request #6006
Opened 2023-06-02 14:50 UTC by zarirhamza

Adds `out.host` tag for celery

2023-06-06 09:25 UTC, jbertran commented on ddtrace/contrib/celery/signals.py
> +            span.set_tag_str(net.TARGET_HOST, host)
I gave you the typo'd version of my diff 🤦 
```suggestion
            span.set_tag_str(net.TARGET_HOST, nodename)
```

2023-06-07 16:36 UTC, mabdinur commented on ddtrace/contrib/celery/signals.py
> +        set_tags_from_context(span, kwargs["headers"])
```suggestion
    if kwargs.get("headers") is not None:
        set_tags_from_context(span, kwargs["headers"])
```

2023-06-07 16:37 UTC, mabdinur commented on ddtrace/contrib/celery/signals.py
> +        set_tags_from_context(span, kwargs["headers"])
```suggestion
    if kwargs.get("headers") is not None:
        set_tags_from_context(span, kwargs["headers"])
```

2023-06-07 16:47 UTC, mabdinur approved these changes

2023-06-07 17:11 UTC, mabdinur requested changes
We should off on merging this PR until the Github incident is resolved.

2023-06-07 18:28 UTC, mabdinur commented on releasenotes/notes/celery-precursor-peer.service-d3b1bc05f1ca59ab.yaml
> +
```suggestion
```

2023-06-07 18:29 UTC, mabdinur approved these changes

2023-06-07 19:07 UTC, merged