fix(django): populate span.resource on forced exit
DataDog/dd-trace-py pull request #6674
Opened 2023-08-15 19:28 UTC by tabgok

This change fixes a behavior where span.resource would not be correctly filled out when django.core.base.handler.BaseHandler.get_response was terminated.  In particular, this issue arose with gunicorn terminating the active worker after a request took more than the worker timeout period (default 10 seconds).

Before change:
    span.resource = "GET"

After Change:
    span.resource = "GET <ENDPOINT>"

## Checklist

- [ ] Change(s) are motivated and described in the PR description.
- [ ] Testing strategy is described if automated tests are not included in the PR.
- [ ] Risk is outlined (performance impact, potential for breakage, maintainability, etc).
- [ ] Change is maintainable (easy to change, telemetry, documentation).
- [ ] [Library release note guidelines](https://ddtrace.readthedocs.io/en/stable/releasenotes.html) are followed. If no release note is required, add label `changelog/no-changelog`.
- [ ] Documentation is included (in-code, generated user docs, [public corp docs](https://github.com/DataDog/documentation/)).
- [ ] Backport labels are set (if [applicable](https://ddtrace.readthedocs.io/en/latest/contributing.html#backporting))

## Reviewer Checklist

- [ ] Title is accurate.
- [ ] No unnecessary changes are introduced.
- [ ] Description motivates each change.
- [ ] Avoids breaking [API](https://ddtrace.readthedocs.io/en/stable/versioning.html#interfaces) changes unless absolutely necessary.
- [ ] Testing strategy adequately addresses listed risk(s).
- [ ] Change is maintainable (easy to change, telemetry, documentation).
- [ ] Release note makes sense to a user of the library.
- [ ] Reviewer has explicitly acknowledged and discussed the performance implications of this PR as reported in the benchmarks PR comment.
- [ ] Backport labels are set in a manner that is consistent with the [release branch maintenance policy](https://ddtrace.readthedocs.io/en/latest/contributing.html#backporting)

2023-08-15 19:39 UTC, emmettbutler requested changes
The changes are looking great. I recommend setting some backport labels and adding a release note.

2023-08-16 13:59 UTC, emmettbutler requested changes

2023-08-16 13:59 UTC, emmettbutler commented on releasenotes/notes/fix-django-span-resource-on-unexpected-terminate-fbc5ce27d503d635.yaml
> +    of timeouts with gunicorn workouts.
```suggestion
    django: This fix resolves an issue where 'span.resource' would not include the endpoint when a Handler was interrupted, such as in the case
    of gunicorn worker timeouts.  
```

2023-08-17 13:50 UTC, emmettbutler submitted a review, later dismissed

2023-08-17 14:38 UTC, jbertran submitted a review, later dismissed

2023-08-17 18:38 UTC, emmettbutler approved these changes

2023-08-18 13:52 UTC, emmettbutler approved these changes

2023-08-20 17:46 UTC, merged