chore: fix wrong version in the docs for automatic login events
DataDog/dd-trace-py pull request #6917
Opened 2023-09-15 09:36 UTC by juanjux

## Checklist

- [X] Change(s) are motivated and described in the PR description.
- [X] Testing strategy is described if automated tests are not included in the PR.
- [X] Risk is outlined (performance impact, potential for breakage, maintainability, etc).
- [X] Change is maintainable (easy to change, telemetry, documentation).
- [X] [Library release note guidelines](https://ddtrace.readthedocs.io/en/stable/releasenotes.html) are followed. If no release note is required, add label `changelog/no-changelog`.
- [X] Documentation is included (in-code, generated user docs, [public corp docs](https://github.com/DataDog/documentation/)).
- [X] Backport labels are set (if [applicable](https://ddtrace.readthedocs.io/en/latest/contributing.html#backporting))

## Reviewer Checklist

- [ ] Title is accurate.
- [ ] No unnecessary changes are introduced.
- [ ] Description motivates each change.
- [ ] Avoids breaking [API](https://ddtrace.readthedocs.io/en/stable/versioning.html#interfaces) changes unless absolutely necessary.
- [ ] Testing strategy adequately addresses listed risk(s).
- [ ] Change is maintainable (easy to change, telemetry, documentation).
- [ ] Release note makes sense to a user of the library.
- [ ] Reviewer has explicitly acknowledged and discussed the performance implications of this PR as reported in the benchmarks PR comment.
- [ ] Backport labels are set in a manner that is consistent with the [release branch maintenance policy](https://ddtrace.readthedocs.io/en/latest/contributing.html#backporting)
- [ ] If this PR touches code that signs or publishes builds or packages, or handles credentials of any kind, I've requested a review from `@DataDog/security-design-and-guidance`.
- [ ] This PR doesn't touch any of that.

2023-09-15 09:45 UTC, jkirsteins submitted a review, later dismissed

2023-09-15 14:42 UTC, emmettbutler requested changes

2023-09-15 14:42 UTC, emmettbutler commented on docs/configuration.rst
> +         set to ``true`` to work. Currently only supported in Django.
This note would be more resilient to future changes if it was on the `1.17.0` item under `version_added`.
```suggestion
         set to ``true`` to work.
```

2023-09-15 14:42 UTC, emmettbutler commented on docs/configuration.rst
> +         v1.17.0:
```suggestion
         v1.17.0: Added support to the Django integration. No other integrations support this configuration.
```

2023-09-26 20:59 UTC, emmettbutler approved these changes

2023-10-02 13:40 UTC, merged