chore(dbm): dbm should use peer.service value when enabled
DataDog/dd-trace-py pull request #6962
Opened 2023-09-20 17:19 UTC by tabgok

DBM adds comments to database commands for the purposes of context propagation.  One of the pieces of information in the comments is the service name of the external database and is used for generating metrics (i.e. # of writes per second to external database).

Prior to this change, DBM relied on the service name being set to the value of span.service.  In auto-instrumented services, this value typically belongs to the fake span generated with the destination database name, such as "postgres".  This caused issues when peer.service is enabled, since the fake span no longer existed.

After this change, DBM will use the precursor for peer.service (if available) when peer service defaults are enabled.

## Checklist

- [ ] Change(s) are motivated and described in the PR description.
- [ ] Testing strategy is described if automated tests are not included in the PR.
- [ ] Risk is outlined (performance impact, potential for breakage, maintainability, etc).
- [ ] Change is maintainable (easy to change, telemetry, documentation).
- [ ] [Library release note guidelines](https://ddtrace.readthedocs.io/en/stable/releasenotes.html) are followed. If no release note is required, add label `changelog/no-changelog`.
- [ ] Documentation is included (in-code, generated user docs, [public corp docs](https://github.com/DataDog/documentation/)).
- [ ] Backport labels are set (if [applicable](https://ddtrace.readthedocs.io/en/latest/contributing.html#backporting))

## Reviewer Checklist

- [ ] Title is accurate.
- [ ] No unnecessary changes are introduced.
- [ ] Description motivates each change.
- [ ] Avoids breaking [API](https://ddtrace.readthedocs.io/en/stable/versioning.html#interfaces) changes unless absolutely necessary.
- [ ] Testing strategy adequately addresses listed risk(s).
- [ ] Change is maintainable (easy to change, telemetry, documentation).
- [ ] Release note makes sense to a user of the library.
- [ ] Reviewer has explicitly acknowledged and discussed the performance implications of this PR as reported in the benchmarks PR comment.
- [ ] Backport labels are set in a manner that is consistent with the [release branch maintenance policy](https://ddtrace.readthedocs.io/en/latest/contributing.html#backporting)
- [ ] If this PR touches code that signs or publishes builds or packages, or handles credentials of any kind, I've requested a review from `@DataDog/security-design-and-guidance`.
- [ ] This PR doesn't touch any of that.

2023-09-21 13:02 UTC, amarziali submitted a review, later dismissed

2023-09-22 16:15 UTC, emmettbutler requested changes

2023-09-22 16:15 UTC, emmettbutler commented on releasenotes/notes/dbm-fix-for-peer-service-ea46572a0daa08ec.yaml
> +#    * Use dynamic links (``stable/latest/1.x`` URLs). Instead, use static links (specific version, commit hash) whenever possible so that they don't break in the future.
```suggestion
```

2023-09-25 13:58 UTC, emmettbutler approved these changes

2023-09-25 14:44 UTC, merged