chore(telemetry): clean up tests
DataDog/dd-trace-py pull request #7458
Opened 2023-11-02 17:38 UTC by mabdinur

ddtrace tests currently use a variety of fixtures to test telemetry functionality. This PR ensures all telemetry tests use the `telemetry_writer` fixture defined in `tests/conftest.py`. 
  - Removes all telemetry configurations from `tests/appsec/conftest.py`. 
  - Converts all instances of `import ddtrace.internal.telemetry import telemetry_writer` to `import ddtrace.internal import telemetry; telemetry.telemetry_writer.....`). This allows us to easily mock the global telemetry writer in unit tests.
  - Updates tests.conftest.telemetry_writer to mock the global telemetry writer `ddtrace.internal.telemetry.telemetry_writer`
  - Removes `_DD_TELEMETRY_WRITER_ADDITIONAL_HEADERS`. This configuration is no longer used in tests. It currently does nothing (actually it makes the tests harder to read so it's worse than nothing).

## Checklist

- [ ] Change(s) are motivated and described in the PR description.
- [ ] Testing strategy is described if automated tests are not included in the PR.
- [ ] Risk is outlined (performance impact, potential for breakage, maintainability, etc).
- [ ] Change is maintainable (easy to change, telemetry, documentation).
- [ ] [Library release note guidelines](https://ddtrace.readthedocs.io/en/stable/releasenotes.html) are followed. If no release note is required, add label `changelog/no-changelog`.
- [ ] Documentation is included (in-code, generated user docs, [public corp docs](https://github.com/DataDog/documentation/)).
- [ ] Backport labels are set (if [applicable](https://ddtrace.readthedocs.io/en/latest/contributing.html#backporting))

## Reviewer Checklist

- [ ] Title is accurate.
- [ ] No unnecessary changes are introduced.
- [ ] Description motivates each change.
- [ ] Avoids breaking [API](https://ddtrace.readthedocs.io/en/stable/versioning.html#interfaces) changes unless absolutely necessary.
- [ ] Testing strategy adequately addresses listed risk(s).
- [ ] Change is maintainable (easy to change, telemetry, documentation).
- [ ] Release note makes sense to a user of the library.
- [ ] Reviewer has explicitly acknowledged and discussed the performance implications of this PR as reported in the benchmarks PR comment.
- [ ] Backport labels are set in a manner that is consistent with the [release branch maintenance policy](https://ddtrace.readthedocs.io/en/latest/contributing.html#backporting)
- [ ] If this PR touches code that signs or publishes builds or packages, or handles credentials of any kind, I've requested a review from `@DataDog/security-design-and-guidance`.
- [ ] This PR doesn't touch any of that.

2023-11-02 20:47 UTC, emmettbutler requested changes

2023-11-02 20:47 UTC, emmettbutler commented on hatch.toml
> +    "mock"
I think you can avoid this dependency by using `unittest.mock` from the Python standard library. If that's right, I'd recommend doing so.

2023-11-02 21:04 UTC, emmettbutler approved these changes

2023-11-03 13:32 UTC, majorgreys approved these changes

2023-11-03 14:03 UTC, merged