[SVLS-4126] Patch botocore stepfunctions
DataDog/dd-trace-py pull request #7514
Opened 2023-11-07 19:11 UTC by agocs

Patch botocore stepfunctions start-execution and start-sync-execution. We want to be able to add trace context to the `input` so the stepfunction logs trace reducer can link stepfunction traces to upstream traces.

## Checklist

- [ ] Change(s) are motivated and described in the PR description.
- [ ] Testing strategy is described if automated tests are not included in the PR.
- [ ] Risk is outlined (performance impact, potential for breakage, maintainability, etc).
- [ ] Change is maintainable (easy to change, telemetry, documentation).
- [ ] [Library release note guidelines](https://ddtrace.readthedocs.io/en/stable/releasenotes.html) are followed. If no release note is required, add label `changelog/no-changelog`.
- [ ] Documentation is included (in-code, generated user docs, [public corp docs](https://github.com/DataDog/documentation/)).
- [ ] Backport labels are set (if [applicable](https://ddtrace.readthedocs.io/en/latest/contributing.html#backporting))

## Reviewer Checklist

- [ ] Title is accurate.
- [ ] No unnecessary changes are introduced.
- [ ] Description motivates each change.
- [ ] Avoids breaking [API](https://ddtrace.readthedocs.io/en/stable/versioning.html#interfaces) changes unless absolutely necessary.
- [ ] Testing strategy adequately addresses listed risk(s).
- [ ] Change is maintainable (easy to change, telemetry, documentation).
- [ ] Release note makes sense to a user of the library.
- [ ] Reviewer has explicitly acknowledged and discussed the performance implications of this PR as reported in the benchmarks PR comment.
- [ ] Backport labels are set in a manner that is consistent with the [release branch maintenance policy](https://ddtrace.readthedocs.io/en/latest/contributing.html#backporting)
- [ ] If this PR touches code that signs or publishes builds or packages, or handles credentials of any kind, I've requested a review from `@DataDog/security-design-and-guidance`.
- [ ] This PR doesn't touch any of that.

2023-11-07 21:21 UTC, majorgreys commented
@agocs Can you add a release note for this feature change?

https://ddtrace.readthedocs.io/en/stable/releasenotes.html#generating-a-release-note

2023-11-14 19:05 UTC, majorgreys commented on releasenotes/notes/inject-botocore-stepfunction-start_execution-calls-95bed0ca2e1d006e.yaml
> +    Add the ability to inject trace context into the input field of botocore stepfunction start_execution and
```suggestion
    botocore: Add the ability to inject trace context into the input field of botocore stepfunction start_execution and 
```

2023-12-01 18:30 UTC, ZStriker19 approved these changes
Is extraction already implemented?

2023-12-01 18:32 UTC, ZStriker19 commented
> Is extraction already implemented?

Oh or there is no extraction?  Because "stepfunction logs trace reducer can link stepfunction traces to upstream traces."

2023-12-04 17:34 UTC, agocs commented
@ZStriker19 That's correct, extraction will be implemented in the logs-to-traces reducer

2023-12-06 22:22 UTC, purple4reina requested changes
Let's do a ducktype check before adding the dd header dict.

Also, looks like we could use more test coverage of this `inject_trace_to_stepfunction_input`. I'm seeing 5 different code paths, yet only one test.

2023-12-11 20:21 UTC, agocs commented on ddtrace/contrib/botocore/patch.py
> +        input_obj["_datadog"] = {}
Good catch! Thanks. Input validation for start_execution is weird and inconsistent, so I'm trying to cast as broad a net as possible. I added additional tests for different possible data types.

2023-12-11 20:21 UTC, agocs commented on tests/contrib/botocore/test.py
> +        assert span.name == "states.command"  # This confirms our patch is working
You're not wrong!

2023-12-11 21:22 UTC, purple4reina approved these changes

2023-12-13 18:40 UTC, emmettbutler approved these changes

2023-12-14 17:33 UTC, agocs commented
I think I'm going to wait until after the code freeze to merge this rather than rush to get it in before EOY.

2024-01-12 18:01 UTC, merged