chore(tracing): report `http.route` in web frameworks
DataDog/dd-trace-py pull request #7795
Opened 2023-11-30 18:17 UTC by jbertran

We want to report the route string of a response in web frameworks, i.e. the raw routing rule that was matched by the request, as the `http.route` tag.

This route may contain:
* a regex-like format different from framework to framework, handling variables in URL contents (for example `/hi/{name}`)
* an application root prepended to the matched route, if the framework handles it (for example, WSGI `SCRIPT_NAME` variable passed through, or some other mechanism of handling the application root `/` being different from the _served_ root)

This adds `http.route` to the frameworks where it was missing and it is easy to implement:
* aiohttp
* bottle
* falcon
* molten

## Checklist

- [x] Change(s) are motivated and described in the PR description.
- [x] Testing strategy is described if automated tests are not included in the PR.
- [x] Risk is outlined (performance impact, potential for breakage, maintainability, etc).
- [x] Change is maintainable (easy to change, telemetry, documentation).
- [x] [Library release note guidelines](https://ddtrace.readthedocs.io/en/stable/releasenotes.html) are followed. If no release note is required, add label `changelog/no-changelog`.
- [x] Documentation is included (in-code, generated user docs, [public corp docs](https://github.com/DataDog/documentation/)).
- [x] Backport labels are set (if [applicable](https://ddtrace.readthedocs.io/en/latest/contributing.html#backporting))

## Reviewer Checklist

- [x] Title is accurate.
- [x] No unnecessary changes are introduced.
- [x] Description motivates each change.
- [x] Avoids breaking [API](https://ddtrace.readthedocs.io/en/stable/versioning.html#interfaces) changes unless absolutely necessary.
- [x] Testing strategy adequately addresses listed risk(s).
- [x] Change is maintainable (easy to change, telemetry, documentation).
- [x] Release note makes sense to a user of the library.
- [x] Reviewer has explicitly acknowledged and discussed the performance implications of this PR as reported in the benchmarks PR comment.
- [x] Backport labels are set in a manner that is consistent with the [release branch maintenance policy](https://ddtrace.readthedocs.io/en/latest/contributing.html#backporting)
- [x] If this PR touches code that signs or publishes builds or packages, or handles credentials of any kind, I've requested a review from `@DataDog/security-design-and-guidance`.
- [x] This PR doesn't touch any of that.

2023-12-01 13:56 UTC, emmettbutler approved these changes

2023-12-05 17:58 UTC, emmettbutler requested changes
I think this could use a release note. Other than that, it's ready to go.

2023-12-06 19:40 UTC, mabdinur approved these changes
It would be nice to report the `http.route` in our urllib3 integration (since urllib3 is part of python standard library). Updating the requests integration would also be nice. 

This isn't a blocker.

2023-12-13 14:46 UTC, jbertran commented
> It would be nice to report the `http.route` in our urllib3 integration (since urllib3 is part of python standard library). Updating the requests integration would also be nice.

@mabdinur the `http.route` tag's purpose is to report web framework routing matches, so they are deliberately excluded.

2023-12-13 19:13 UTC, emmettbutler approved these changes

2023-12-14 13:46 UTC, merged