refactor: add ancestor runtime ID
DataDog/dd-trace-py pull request #7931
Opened 2023-12-14 16:53 UTC by P403n1x87

Because of the current implementation of the remote configuration client, configuration requests are made by the common ancestor process. This means that child processes are invisible to the RCM backend. Some products require information about the runtime ID to provide a good UX. We add the possibility of retrieving the runtime ID of the common ancestor process (the one that will communicate with the RCM backend) from any child so that its runtime ID can be correlated with the ancestor, and used by backend services that rely on the enablement signal coming from RCM requests.

## Checklist

- [ ] Change(s) are motivated and described in the PR description.
- [ ] Testing strategy is described if automated tests are not included in the PR.
- [ ] Risk is outlined (performance impact, potential for breakage, maintainability, etc).
- [ ] Change is maintainable (easy to change, telemetry, documentation).
- [ ] [Library release note guidelines](https://ddtrace.readthedocs.io/en/stable/releasenotes.html) are followed. If no release note is required, add label `changelog/no-changelog`.
- [ ] Documentation is included (in-code, generated user docs, [public corp docs](https://github.com/DataDog/documentation/)).
- [ ] Backport labels are set (if [applicable](https://ddtrace.readthedocs.io/en/latest/contributing.html#backporting))

## Reviewer Checklist

- [ ] Title is accurate.
- [ ] No unnecessary changes are introduced.
- [ ] Description motivates each change.
- [ ] Avoids breaking [API](https://ddtrace.readthedocs.io/en/stable/versioning.html#interfaces) changes unless absolutely necessary.
- [ ] Testing strategy adequately addresses listed risk(s).
- [ ] Change is maintainable (easy to change, telemetry, documentation).
- [ ] Release note makes sense to a user of the library.
- [ ] Reviewer has explicitly acknowledged and discussed the performance implications of this PR as reported in the benchmarks PR comment.
- [ ] Backport labels are set in a manner that is consistent with the [release branch maintenance policy](https://ddtrace.readthedocs.io/en/latest/contributing.html#backporting)
- [ ] If this PR touches code that signs or publishes builds or packages, or handles credentials of any kind, I've requested a review from `@DataDog/security-design-and-guidance`.
- [ ] This PR doesn't touch any of that.

2023-12-14 19:24 UTC, shatzi reviewed
nice!
should we also update the probe-status messages?

2023-12-14 23:26 UTC, P403n1x87 commented
> nice! should we also update the probe-status messages?

Yep, we'll do that in #7912

2023-12-18 14:54 UTC, ZStriker19 commented on ddtrace/internal/runtime/__init__.py
> +    Once this values is set (this will happen after a fork) it will not change
```suggestion
    Once this value is set (this will happen after a fork) it will not change
```

2023-12-18 15:43 UTC, majorgreys reviewed
Being the changes are internal features, should we title this PR differently?

2023-12-19 14:51 UTC, majorgreys requested changes
Change the PR title to a chore to be consistent with the convention we have been using recently for "internal", non-public facing feature work (which this seems to be if I am following).

2023-12-20 16:14 UTC, majorgreys approved these changes

2023-12-20 17:07 UTC, merged