Fix asyncpg patch for asyncpg.Pool instances
DataDog/dd-trace-py pull request #8028
Opened 2024-01-06 02:25 UTC by ekzhang

Hello! I noticed that using `ddtrace.patch(asyncpg=True)` doesn't work as expected with connection pools, the most common way of using asyncpg database connections.

I'm trying to use `Pin.override()` on the connection object when it is created, which works for direct connections created with `asyncpg.connect()`. However, it does not work with pooled connections.

```python
import asyncpg
import ddtrace
from ddtrace import Pin

ddtrace.patch(asyncpg=True)

async def init_db_connection(conn):
        # print("DEBUG:", getattr(conn, "__getddpin__", None))
        Pin.override(conn, service="my-database-123")  # Let Datadog know what service this is.

pool = await asyncpg.create_pool(dsn="postgres://...", init=init_db_connection)
async with pool.acquire() as conn:
    await conn.fetch(...)
```

This Pin `service` override doesn't work with pools, even though it works with ordinary connections. If you uncomment the `DEBUG:` line above, you can see that the `__getddpin__` method is not present on the connection objects from a pool, even though it is on other asyncpg connections.

I noticed it's because of this [line of code](https://github.com/MagicStack/asyncpg/blob/d7faaff57a7a9c0029a31f09564d30ab35007907/asyncpg/pool.py#L501-L508) from asyncpg.Pool, which calls `asyncpg.connection.connect()`. But ddtrace only patches `asyncpg.connect()`, which is an alias for that.

We need to patch both methods for it to work!

## Checklist

- [x] Change(s) are motivated and described in the PR description.
- [x] Testing strategy is described if automated tests are not included in the PR.
- [x] Risk is outlined (performance impact, potential for breakage, maintainability, etc).
- [x] Change is maintainable (easy to change, telemetry, documentation).
- [x] [Library release note guidelines](https://ddtrace.readthedocs.io/en/stable/releasenotes.html) are followed. If no release note is required, add label `changelog/no-changelog`.
- [x] Documentation is included (in-code, generated user docs, [public corp docs](https://github.com/DataDog/documentation/)).
- [x] Backport labels are set (if [applicable](https://ddtrace.readthedocs.io/en/latest/contributing.html#backporting))

## Reviewer Checklist

- [ ] Title is accurate.
- [ ] No unnecessary changes are introduced.
- [ ] Description motivates each change.
- [ ] Avoids breaking [API](https://ddtrace.readthedocs.io/en/stable/versioning.html#interfaces) changes unless absolutely necessary.
- [ ] Testing strategy adequately addresses listed risk(s).
- [ ] Change is maintainable (easy to change, telemetry, documentation).
- [ ] Release note makes sense to a user of the library.
- [ ] Reviewer has explicitly acknowledged and discussed the performance implications of this PR as reported in the benchmarks PR comment.
- [ ] Backport labels are set in a manner that is consistent with the [release branch maintenance policy](https://ddtrace.readthedocs.io/en/latest/contributing.html#backporting)
- [ ] If this PR touches code that signs or publishes builds or packages, or handles credentials of any kind, I've requested a review from `@DataDog/security-design-and-guidance`.
- [ ] This PR doesn't touch any of that.

2024-01-06 02:31 UTC, ekzhang commented
(cc @aksh-at this is why APM traces are still mixed up)

2024-01-08 14:18 UTC, emmettbutler requested changes
Thank you for the contribution, @ekzhang! With a few additions, we could certainly merge this.

* With Docker running, try prefixing your riot command with `scripts/ddtest pip install riot && `. This will run the command inside of a container that is provisioned to be able to make release notes.
* Consider adding a regression test that verifies that the new patching is having the intended effect.

Let me know if you'd like any assistance with either of these. Cheers!

2024-01-08 15:18 UTC, ekzhang commented
I just made a best effort to add tests as you advised, though I can't run them at the moment — running tests and generating the release note file name don't seem possible right now as an external contributor since I can't get feedback from your development scripts.

2024-01-31 14:24 UTC, ekzhang commented
Hi, we didn't get a response. We have been vendoring this patch in our own codebase now. Given the bugs and inscrutability of datadog's client libraries, we're going to look to other vendors.

2024-01-31 14:24 UTC, closed without merging