fix(setup): remove metadata redundancy
DataDog/dd-trace-py pull request #8567
Opened 2024-03-01 11:11 UTC by P403n1x87

We remove metadata redundancy in setup.py and move it as much as possible into pyproject.toml. This is crucial for dependencies, since their declaration in pyproject.toml overrides setup.py.

## Checklist

- [ ] Change(s) are motivated and described in the PR description
- [ ] Testing strategy is described if automated tests are not included in the PR
- [ ] Risks are described (performance impact, potential for breakage, maintainability)
- [ ] Change is maintainable (easy to change, telemetry, documentation)
- [ ] [Library release note guidelines](https://ddtrace.readthedocs.io/en/stable/releasenotes.html) are followed or label `changelog/no-changelog` is set
- [ ] Documentation is included (in-code, generated user docs, [public corp docs](https://github.com/DataDog/documentation/))
- [ ] Backport labels are set (if [applicable](https://ddtrace.readthedocs.io/en/latest/contributing.html#backporting))
- [ ] If this PR changes the public interface, I've notified `@DataDog/apm-tees`.
- [ ] If change touches code that signs or publishes builds or packages, or handles credentials of any kind, I've requested a review from `@DataDog/security-design-and-guidance`.

## Reviewer Checklist

- [ ] Title is accurate
- [ ] All changes are related to the pull request's stated goal
- [ ] Description motivates each change
- [ ] Avoids breaking [API](https://ddtrace.readthedocs.io/en/stable/versioning.html#interfaces) changes
- [ ] Testing strategy adequately addresses listed risks
- [ ] Change is maintainable (easy to change, telemetry, documentation)
- [ ] Release note makes sense to a user of the library
- [ ] Author has acknowledged and discussed the performance implications of this PR as reported in the benchmarks PR comment
- [ ] Backport labels are set in a manner that is consistent with the [release branch maintenance policy](https://ddtrace.readthedocs.io/en/latest/contributing.html#backporting)

2024-03-01 14:55 UTC, emmettbutler reviewed
How did you confirm that both installation methods still work after this change?

2024-03-05 13:30 UTC, emmettbutler approved these changes

2024-03-05 14:37 UTC, ofek commented on pyproject.toml
> +    "bytecode>=0.14.0; python_version>='3.11'",
```suggestion
    "bytecode>=0.15.0; python_version~='3.12.0'",
    "bytecode>=0.14.0; python_version~='3.11.0'",
```

2024-03-05 14:40 UTC, ofek requested changes

2024-03-05 14:40 UTC, ofek commented on pyproject.toml
> +    "bytecode>=0.13.0",
```suggestion
    "bytecode>=0.14.0; python_version~='3.11.0'",
    "bytecode>=0.13.0; python_version<'3.11'",
```

2024-03-05 17:29 UTC, ofek approved these changes

2024-03-06 19:16 UTC, majorgreys approved these changes

2024-03-07 10:03 UTC, merged