chore(asm): improve api security import condition (#8609)
DataDog/dd-trace-py pull request #8641
Opened 2024-03-07 12:56 UTC by christophe-papazian

Following https://github.com/DataDog/dd-trace-py/pull/8226, this PR ensure that we never import api security manager module if the WAF is unavailable or asm is disabled or api security is disabled.

- Add one finite state (bool) to the asm config `_api_security_active` to keep track of API Security Manager
- Update and check that state in `_default_span_processors_factory`.

## Checklist

- [x] Change(s) are motivated and described in the PR description
- [x] Testing strategy is described if automated tests are not included in the PR
- [x] Risks are described (performance impact, potential for breakage, maintainability)
- [x] Change is maintainable (easy to change, telemetry, documentation)
- [x] [Library release note guidelines](https://ddtrace.readthedocs.io/en/stable/releasenotes.html) are followed or label `changelog/no-changelog` is set
- [x] Documentation is included (in-code, generated user docs, [public corp docs](https://github.com/DataDog/documentation/))
- [x] Backport labels are set (if [applicable](https://ddtrace.readthedocs.io/en/latest/contributing.html#backporting))
- [x] If this PR changes the public interface, I've notified `@DataDog/apm-tees`.
- [x] If change touches code that signs or publishes builds or packages, or handles credentials of any kind, I've requested a review from `@DataDog/security-design-and-guidance`.

## Reviewer Checklist

- [x] Title is accurate
- [x] All changes are related to the pull request's stated goal
- [x] Description motivates each change
- [x] Avoids breaking [API](https://ddtrace.readthedocs.io/en/stable/versioning.html#interfaces) changes
- [x] Testing strategy adequately addresses listed risks
- [x] Change is maintainable (easy to change, telemetry, documentation)
- [x] Release note makes sense to a user of the library
- [x] Author has acknowledged and discussed the performance implications of this PR as reported in the benchmarks PR comment
- [x] Backport labels are set in a manner that is consistent with the [release branch maintenance
policy](https://ddtrace.readthedocs.io/en/latest/contributing.html#backporting)

(cherry picked from commit 9d5ff05ec61e9fdb9c331c90b0882e15a5c28ffb)

2024-03-07 13:35 UTC, gnufede requested changes

2024-03-07 13:35 UTC, gnufede commented on ddtrace/_trace/tracer.py
Backporting this entire file seems off

2024-03-07 20:28 UTC, emmettbutler approved these changes

2024-03-08 08:42 UTC, gnufede approved these changes

2024-03-08 09:05 UTC, merged