fix(internal): fix CI Visibility usage of the core API
DataDog/dd-trace-py pull request #9162
Opened 2024-05-06 13:19 UTC by brettlangdon

Fixes some small inconsistencies with the core api usage in CI Visibility.

1. A call to `dispatch_with_results` when no value is expected to be returned (small performance optimization to avoid building a results dictionary when it isn't needed).
2. A call to `dispatch_with_results` which would not return the underlying listener value
    a. (I _think_ it would always return a falsey value since it should have been returning the `core._MissingEvent` `EventResult` which is falsey and which has a value of `None`... ?)

I am not sure which tests should be evaluated/updated, since I am surprised there weren't any failing tests before, there _should_ have been.

## Checklist

- [x] Change(s) are motivated and described in the PR description
- [ ] Testing strategy is described if automated tests are not included in the PR
- [x] Risks are described (performance impact, potential for breakage, maintainability)
- [x] Change is maintainable (easy to change, telemetry, documentation)
- [x] [Library release note guidelines](https://ddtrace.readthedocs.io/en/stable/releasenotes.html) are followed or label `changelog/no-changelog` is set
- [x] Documentation is included (in-code, generated user docs, [public corp docs](https://github.com/DataDog/documentation/))
- [x] Backport labels are set (if [applicable](https://ddtrace.readthedocs.io/en/latest/contributing.html#backporting))
- [x] If this PR changes the public interface, I've notified `@DataDog/apm-tees`.

## Reviewer Checklist

- [ ] Title is accurate
- [ ] All changes are related to the pull request's stated goal
- [ ] Description motivates each change
- [ ] Avoids breaking [API](https://ddtrace.readthedocs.io/en/stable/versioning.html#interfaces) changes
- [ ] Testing strategy adequately addresses listed risks
- [ ] Change is maintainable (easy to change, telemetry, documentation)
- [ ] Release note makes sense to a user of the library
- [ ] Author has acknowledged and discussed the performance implications of this PR as reported in the benchmarks PR comment
- [ ] Backport labels are set in a manner that is consistent with the [release branch maintenance policy](https://ddtrace.readthedocs.io/en/latest/contributing.html#backporting)

2024-05-07 15:06 UTC, emmettbutler approved these changes
Oh yeah, it's not clear at all to me why this isn't causing `test_is_item_itr_skippable_test_level` to fail in current main. This change does look more correct, though.

2024-05-14 07:50 UTC, romainkomorndatadog commented on ddtrace/ext/ci_visibility/api.py
> +        core.dispatch("ci_visibility.session.get_settings", (item_id,))
The actual fix here is to actually return the settings.

2024-05-14 07:50 UTC, romainkomorndatadog requested changes
These (the settings request) aren't in use yet so they're not tested (and, clearly, not working either).

edit: the external API `is_item_itr_skippable()` static method (that ends up calling `core.dispatch_with_results("ci_visibility.itr.is_item_skippable")` itself) is also not tested yet.

`test_is_item_itr_skippable_test_level` is directly testing the `CIVisibility.is_item_itr_skippable()` function directly (which is why it's in `test_ci_visibility.py`), so any changes in this PR wouldn't affect its results.

I'll take over the PR.

2024-05-14 07:59 UTC, romainkomorndatadog commented on ddtrace/ext/ci_visibility/api.py
> +        core.dispatch("ci_visibility.session.get_settings", (item_id,))
Actually, since I don't have a use case for this at the moment, I'm just going to delete it.

2024-05-14 15:00 UTC, romainkomorndatadog commented
Renaming this to a `chore` because this API isn't released yet, so it's not a "fix".

2024-05-14 15:01 UTC, romainkomorndatadog approved these changes

2024-05-15 15:24 UTC, emmettbutler approved these changes

2024-05-15 15:57 UTC, merged