chore: privatize public functions in consul and botocore patch.py
DataDog/dd-trace-py pull request #9915
Opened 2024-07-23 21:03 UTC by rachelyangdog

The API should just be what is necessary. A lot of integrations expose implementation details through the patch.py We can’t just remove these functions right away as it will break our API so for each we will need to deprecate first and then remove in 2.x.

## Checklist
- [ ] PR author has checked that all the criteria below are met
- The PR description includes an overview of the change
- The PR description articulates the motivation for the change
- The change includes tests OR the PR description describes a testing strategy
- The PR description notes risks associated with the change, if any
- Newly-added code is easy to change
- The change follows the [library release note guidelines](https://ddtrace.readthedocs.io/en/stable/releasenotes.html)
- The change includes or references documentation updates if necessary
- Backport labels are set (if [applicable](https://ddtrace.readthedocs.io/en/latest/contributing.html#backporting))

## Reviewer Checklist
- [ ] Reviewer has checked that all the criteria below are met 
- Title is accurate
- All changes are related to the pull request's stated goal
- Avoids breaking [API](https://ddtrace.readthedocs.io/en/stable/versioning.html#interfaces) changes
- Testing strategy adequately addresses listed risks
- Newly-added code is easy to change
- Release note makes sense to a user of the library
- If necessary, author has acknowledged and discussed the performance implications of this PR as reported in the benchmarks PR comment
- Backport labels are set in a manner that is consistent with the [release branch maintenance policy](https://ddtrace.readthedocs.io/en/latest/contributing.html#backporting)

2024-07-24 13:30 UTC, emmettbutler requested changes
Looks great, thanks for the contribution! Since there are deprecations, this change needs to include a release note.

2024-07-24 18:07 UTC, ZStriker19 commented on tests/contrib/consul/test_consul_patch.py
> +from ddtrace.contrib.consul import _get_version
```suggestion
from ddtrace.contrib.consul.patch import _get_version
```

2024-07-24 18:55 UTC, rachelyangdog commented on releasenotes/notes/deprecate-patch-py-functions-consul-botocore-da36c9501c7fc279.yaml
@emmettbutler release notes!

2024-07-25 13:55 UTC, emmettbutler approved these changes

2024-07-25 14:49 UTC, ZStriker19 commented on releasenotes/notes/deprecate-patch-py-methods-consul-botocore-da36c9501c7fc279.yaml
> +    botocore: All methods in botocore/patch.py except patch() and unpatch() are deprecated and will be removed in version 3.0.0.
```suggestion
    botocore: All methods in botocore/patch.py except ``patch()`` and ``unpatch()`` are deprecated and will be removed in version 3.0.0.
```

2024-07-25 14:50 UTC, ZStriker19 commented on releasenotes/notes/deprecate-patch-py-methods-consul-botocore-da36c9501c7fc279.yaml
> +    consul: All methods in consul/patch.py except patch() and unpatch() are deprecated and will be removed in version 3.0.0.
```suggestion
    consul: All methods in consul/patch.py except ``patch()`` and ``unpatch()`` are deprecated and will be removed in version 3.0.0.
```

2024-07-25 14:50 UTC, ZStriker19 approved these changes

2024-07-25 17:09 UTC, merged