fix(botocore): fix botocore kinesis parenting
DataDog/dd-trace-py pull request #9979
Opened 2024-07-29 22:50 UTC by wconti27

## Checklist
- [ ] PR author has checked that all the criteria below are met
- The PR description includes an overview of the change
- The PR description articulates the motivation for the change
- The change includes tests OR the PR description describes a testing strategy
- The PR description notes risks associated with the change, if any
- Newly-added code is easy to change
- The change follows the [library release note guidelines](https://ddtrace.readthedocs.io/en/stable/releasenotes.html)
- The change includes or references documentation updates if necessary
- Backport labels are set (if [applicable](https://ddtrace.readthedocs.io/en/latest/contributing.html#backporting))

## Reviewer Checklist
- [ ] Reviewer has checked that all the criteria below are met 
- Title is accurate
- All changes are related to the pull request's stated goal
- Avoids breaking [API](https://ddtrace.readthedocs.io/en/stable/versioning.html#interfaces) changes
- Testing strategy adequately addresses listed risks
- Newly-added code is easy to change
- Release note makes sense to a user of the library
- If necessary, author has acknowledged and discussed the performance implications of this PR as reported in the benchmarks PR comment
- Backport labels are set in a manner that is consistent with the [release branch maintenance policy](https://ddtrace.readthedocs.io/en/latest/contributing.html#backporting)

2024-07-30 15:53 UTC, emmettbutler requested changes

2024-07-30 15:53 UTC, emmettbutler commented on ddtrace/contrib/botocore/services/kinesis.py
>          parent_ctx.end()
I think this should be removed because it's now an undocumented side effect that mutates one of this function's arguments.

2024-07-31 15:22 UTC, emmettbutler approved these changes

2024-07-31 18:38 UTC, mabdinur approved these changes

2024-07-31 18:38 UTC, merged